const phrases = [
  `Years of logging had left the mountains prone to mudslides | Susceptible, vulnerable, liable`,
  `We have a briefer who will be able to go into this in greater detail
    | Tenemos un informante que podrá entrar en esto con mayor detalle`,
  `misusing | Use (something) in the wrong way or for the wrong purpose`,
  `Instantiated | Represen as or by an instance`,
  `Merely | Just, only`,
  `Likewise | In the same way, also`,
  `Cumbersome | Large or heavy and therefore difficult to carry or use; Unwieldy; Uncomfortable; Awkward`,
  `She suffered from abdominal bloating | A swollen state caused by retention of fluid or gas;`,
  `Shift the focus | To change`,
  `Furthermore | In addition, Besides (Used to introduce a fresh consideration in an argument)`,
  `Even though`,
  `blew up | Explotó`,
  `to be fair | Para ser justo`,
  `It is a bit misleading | Es un poco engañoso`,
  `Upsetting: A painful and upsetting divorce | Causing unhappiness, disappointment, or worry`,
  `Spread blatant untruths | Difundir mentiras flagrantes`,
  `disregarding | Pay no attention to; ignore; Sin tener en cuenta`,
  `frankly stated | Francamente dicho`,
  `spread around | Diseminar`,
  `reiterate | Say something again or a number of times`,
  `take a bit of fiddling with ... | Requiere un poco de manipulación`,
  `worrisome | Inquietante`,
  `Admittedly | Used to introduce a concession or recognition that something is true or is the case; Cierto es que...`,
  `It is only viable`,
  `unwieldy | Difficult to carry or move because of its size, shape or weight`,
  `The reason for this claim seems to be | La razón de esta afirmación parece ser`,
  `skeptical`,
  `if you end up not liking it | Si al final no lo vinculas`,
  `Delving into | Profundizar`,
  `nuances | A subtle difference in or shade or meaning, expression, or sound; Matices`,
  `widely | Ampliamente`,
  `neglected: some severely neglected children; A neglected area of research | Suffering a lack of proper care`,
  `last but not least | Último pero no menos importante`,
  `sleuthing | Careful investigation into a crime or mystery`,
  `under the hood`,
  `In short term | A corto plazo`,
  `It all comes down to ... | Todo se reduce a...`,
  `That's as far as it goes | Eso es lo más lejos que llega`,
  `from the shape`,
  `in the shape of something: Luckily, help arrived in the shape of a police officer | In the form of something, or appearing as something`,
  `Whilst | Mientras que`,
  `factually correct | Facticamente correcta; With regard to what is actually the case, in relation to fact`,
  `tailored | A medida (of clothes) smart, fitted, and well cut`,
  `Thus | As a result or consequence of this; therefore: De este modo`,
  `add up | Agregar, tener sentido, calcular`,
  `Break down the problem`,
  `We're not aiming or perfect`,
  `thoughtful | Considerado`,
  `curated listicles | Listas seleccionadas`,
  `straightforward: A straightforward young man; In a straightforward case no fees will be charged
    | Uncomplicated and easy to do or understand; Directo: Un joven sencillo`,
  `Its dependencies remain unchanged | ...permanecen sin cambios`,
  `leverage: The organization needs to leverage its key resources | use (something) to maximum advantage`,
  `do either of the following | Hacer cualquiera de las siguientes...`,
  `towards | hacia...`,
  `eagerly: Fans of the show are eagerly awaiting the new season | Used to emphasize a strong desire to do or have something`,
  `in eiteher case | En cualquier caso`,
  `reliably | Consistently good in quality or performance; able to be trusted`,
  `entitled | Believing oneself to be inherently deserving of privileges or special treatment (Con Derecho)`,
  `a tough spot | Situación dificil`,
  `halt: A halt in production; There is growing pressure to halt the blodshed | Bring or come to an abrupt stop`,
  `thoroughly: I thoroughly enjoyed the day; He searched the house thoroughly | In an thorough manner; Very much; greatly (Minuciosamente)`,
  `thwart | Prevent (someone) from accomplishing something (Frustrar)`,
  `pesky | damn; fucking (maldito)`,
  `daunting | Seeming difficult to deal with in anticipation (desalentador)`,
  `lean:  | Be in or move into a sloping position (inclinar)`,
  `debt: I paid off my debts | Something, typically money, that is owed or due`,
  `Owed | Have an obligation to pay or repay (something, especially money) in return for something received`,
  `due | Expected at or planned for at a certain time; (Pendiente, Debido)`,
  `swiftly | At high speed; quickly`,
  `endeavours: He is endeavoring to help the Third World; | Try hard to do or achieve something; An attempt to achieve a goal`,
  `pinpoint: One flare had pinpointed the target; | A tiny dot or point; Absolutely precise; to the finest degree; Find or locate exactly`,
  `fairly straightforward | Bastante sencillo(a)`,
  `behave this way`,
  `vacuously | vacíamente`,
  `pun | Make a joke exploiting the different posible meanings of a word`,
  `pun intended | Juego de palabras intencionado`,
  `counterintuitive | Contradictorio`,
  `Regardless | A pesar de todo`,
  `to be aware | Ser conscientes`,
  `beforehand: Rooms must be booked beforehand | antemano`,
  `strengthened | Make or become stronger (Fortificado)`,
  `idle | (Of a person) avoiding work; lazy; Spend time doing nothig (inactivo(a))`,
  `chaining: She chained her bicycle to the railing `,
  `ground up | Molido`,
  `signpost | Señalizar`,
  `caveats: There are a number of caveats which concern the validity of the assessment results
    | A warning or proviso of specific stipulations, conditions, or limitations (advertencia)`,
  `Assessment: The assessment of educational needs | The evaluation or estimation of the nature, quality, or ability of someone or something`,
  `What are they to begin with?`,
  `abstract away`,
  `comprehend | Understand`,
  `tirelessly; Tireless | Incansable; Infatigable`,
  `it's a pity | Es una pena`,
  `unbearable: The heat was getting unbearable | Not able to be endured or tolerated`,
  `off it goes | Se va; Se marcha`,
  `you're willing | Estas dispuesto(a)`,
  `It's up to you | Tu decides`,
  `It will kick in | Se activará`,
  `the stale value | El valor obsoleto`,
  `clear out | Aclarar`,
  `arguably | Posiblemente`,
  `tempted (sometimes you might feel tempted to...)
    | Entice or attempt to entice (someone) to do or acquire something that they find attractive but know to be wrong or not beneficial (Tentado(a))`,
  `Entice | Attract or tempt by offering pleasure or advantage (Atraer)`,
  `resilient`,
  `It doesn't end up being rendered`,
  `altogether | Completely; Totally`,
  `keep an eye out | Estar atento`,
  `though | Aunque`,
  `mandatory: Wearing helmets was made mandatory for cyclists | Required by law or rules; Compulsory`,
  `dust off | Desempolvar`,
  `although | A pesar de`,
  `fiddlings | Jugueteos`,
  `fiddling around | Jugueteando`,
  `kinda | Un poco`,
  `stay out | Quedarse afuera`,
  `wearing off | Desapareciendo`,
  `the poison should wear off in 5 minutes`,
  `he was paid off | Le pagaron`,
  `go off; went off | Follow (seguir)`,
  `the gun just went off | El arma se acaba de disparar`,
  `So you get better results for what you're wanting`,
  `what do you fancy...?  | opposite of "hate"`,
  `dance the night away | all the night`,
  `taking the law into our own hands`,
  `Want to give it another go? | Dar otra oportunidad`,
  `I grew up in Ver`,
  `It turns out I do, It surprises | Resulta que si, es una sorpresa`,
  `Do you get on[along] well with your family? | Get on with ...llevarse bien`,
  `We see one another at... | Nos vemos en ...`,
  `We always fight[another verb] with each other`,
  `How do you know each other?`,
  `They dont see each other often`,
  `They see one another every weekend`,
  `You are so kind`,
  `He is so polite`,
  `Cara's fun | Someone who makes you happy to be around them`,
  `my mom is very funny | Someone woho has a good sense of humour and makes you laugh`,
  `They yielded two key realizations | De ellos se desprenden dos conclusiones clave`,
  `But those benefits come with some pretty hefty tradeoffs | ...compensaciones bastantes importantes`,
  `tackle: Police have launched an initiative to tackle rising crime | Make determined efforts to deal with (a problem or difficult task) (Abordar; Hacer frente)`,
  `without relyng on | Sin depender de`,
  `crowd | Multitud`,
  `you have no clue | No tienes idea`,
  `stay sane | Mantente cuerdo`,
  `Despite | A pesar de`,
  `The job hunt | La búsqueda de empleo`,
  `Struggle: There were signs of a struggle and there was a lot of blood around | (Lucha)`,
  `Stale React component state | (previous state, i think so...)`,
  `We can get rid of some of that cruft by... | Get rid of: Deshacerse; `,
  `Cruft | Badly designed, unnecessarily complicated, or unwanted code or software`,
  `flawed | Blemished, damaged, or imperfect in some way (Defectuoso)`,
  `move around`,
  `Ruthlessly | sin piedad`,
  `negligible | So small or unimportantj as to be not worth considering; insignificant (despreciable)`,
  `jitter | Feelings of extreme nervousness`,
  `arose from | Surgió de`,
  `this change shoved off another... | Este cambio empujó a otro`,
  `can seem a bit daunting... | Puede parecer un poco desalentador`,
  `happen off | Suceder`,
  `who paved the way | Que preparó el camino`,
  `Stockpile | A large accumulated stock of goods or materials (Reservas)`,
  `brittle | Hard but liable to break or shatter easily (Fragil)`,
  `wind up | Terminar, concluir`,
  `It all boils down to... | Todo se reduce a...`,
  `to wander | Walk or move in a leisurely, casual, or aimless way (vagar)`,
  `Aimless | Sin rumbo`,
  `Leisurely | Tranquilo, Sin prisa`,
  `to haunt you | Para perseguirte...`,
  `trip each other up | Tropezar unos con otros`,
  `can be reasoned about | Se puede razonar sobre`,
  `outcomes predicted | Resultados previstos`,
  `we get way better... | Nos volvemos mucho mejores`,
  `the market is tough | tough = duro`,
  `come off | Salir`,
  `upbeat | Optimistic`,
  `pump yourself up | Anímate`,
  `highest bidder | Mejor postor`,
  `regarding the... | Con respecto a...`,
  `Companies are biased toward hiring people with right attitude | ...estan dispuestas a contratar...`,
  `strive | Make great efforts to achieve or obtain something (Esforzarse)`,
  `thorough | Complete with regard to every detail, not superficial or partial (Exhaustiva)`,
  `drifted away from... | Se alejó de...`,
  `blissful | Extremely happy; full or joy`,
  `spite: He'd think I was saying it out of spite | A desire to hurt, annoy, or offend someone (Despecho)`,
  `tongue cheek stab | Puñalada en la mejilla`,
  `where can I find the fitting room? | ...probador`,
  `Their shoes don't match their dresses or bags, but it suits them!`,
  `It loked really in style and matched my brown skirt!`,
  `The fitting room's at the end of the shop on the right`,
  `Pure functions are functions which obey two laws | ...obedece a dos leyes`,
  `The fundamental building block we build our applications with`,
  `How would you like to ...`,
  `That's a reasonable price for those shoes`,
  `That word "reasonable" describes an item that is neither cheap nor expensive`,
  `The designer store has a sale on, so prices are more reasonable`,
  `This traffic is the worst I've seen yet, I'd better...`,
  `Would you like a receipt emailed to you?`,
  `Dou you want me to print or email the receipt?`,
  `And the real you made fun of my pie suit | Y la verdad es que te burlaste de mi traje pastel`,
  `The word "crowded" can mean that there are a lot of people or too many people in one place`,
  `The school's sports day is held at a large venue | ...se celebra en un gran recinto`,
  `life out here is very different than life in the city`,
  `I am getting better at (it) | Estoy mejorando`,
  `Around the corner = very close (place)`,
  `There's a new cafe on the way to the university`,
  `She passes a post office whilst travelling to work`,
  `the supermarket is just down the street from my apartment`,
  `I'll get breakfast on the way to work`,
  `the pharmacy is on the other side of the shopping centre`,
  `My parents live ON Quenn Street`,
  `Have you come across any nice places to eat here? | encontrar`,
  `"to come across" means to find something by chance | Encontrar algo por casualidad`,
  `Sometimes we come across something by chance`,
  `Sometimes an especially nice place is not very well known, we can call these places "finds" or "hidden gems"`,
  `What a great find`,
  `Have you tried that new restaurant yet?`,
  `There's a supermarket just down the road from my apartment`,
  `Around the corner from my house is a really nice place..s`,
  `He owes us an appetizzer | Nos debe un aperitivo`,
  `Thanks fot that severance check | Cheque de indemnización`,
  `He used his severance money to start a ...`,
  `that i have some concerns | Tengo algunas preocupaciones`,
  `What i'm getting at, ... | A lo que me refiero...`,
  `my train was delayed by 30 minutes`,
  `Am I able to get a refund?`,
  `We are sorry to announce...`,
  `We are sorry for any incovenience...this may cause`,
  `...has been cancelled due to technical issues...`,
  `We are arranging a replacement bus service for ... | ...arreglando...`,
  `To go away for the weekend.`,
  `I think we'll eat lots of local food at the supermarket`,
  `the workflow here is pretty straightforward`,
  `eavesdropping | Escuchando a escondidas`,
  `He delves into the ... | Profundiza`,
  `This seemingly simple action lies a ... | Esta acción aparentemente simple supone una ...`,
  `with seamless integration... | Con integración perfecta`,
  `By the time you finish...`,
  `A dead giveaway that a function is inpure... | Un claro indicio de que ...`,
  `It was suddenly all the rage | De repente estaba de moda`,
  `If a function were to mutate a property... | Si una función mutara...`,
  `which could screw up something | Que podría arruinar algo`,
  `throughout your career | A lo largo de tu carrera`,
  `take pride in your work | Sientete orgulloso de tu trabajo`,
  `be willing to learn | Estar dispuesto a aprender`,
  `We decided to go away to XXx this weekend`,
  `We arraive at 10pm, if our flights aren't delayed`,
  `do you want me to quickly summarize for you? | Resumir`,
  `step towards | -> `,
  `It gets wiped out in memory | (erased from memory)`,
  `Conversely | (in another hand)`,
  `It's important not to confuse`,
  `We like to go on holiday in the summer`,
  `slight differences`,
  `to go on a cruise | Crucero`,
  `We can use "to go" to suggest travelling and enganging in an activity.`,
  `We use "to go on" for a specific type of journey, especially an organised event`,
  `The phrase "to go to" indicates moving towards a particular destination`,
  `She wants to go camping`,
  `He doesn't want to go on a cruise`,
  `The love to go to the beach`,
  `I'd wager that's some sort of a code... | Apuesto a que es ...`,
  `you may yet meet your match | Es posible que aun conozcas a tu pareja`,
  `Would that be some sort of defense against...?`,
  `subtle change (b is silent) | Cambio sutil`,
  `for the job and hand`,
  `tangled up | Enredado`,
  `mingling data | Mezclando datos`,
  `if the user screw up.. (make a mistake)`,
  `stale data | Obsolete`,
  `It's a lot more clear what's going on | `,
  `rest assured | Está seguro`,
  `they can really add up | Ellos realmente pueden sumar`,
  `dodged | Avoid (someone or something) by a sudden quick movement (Desviar)`,
  `worth a gist | Vale la pena`,
  `Which you've just seen an example of | Del cual acabas de ver un ejemplo`,
  `everything is as it should be`,
  `Scratch the surface`,
  `At the very least | Por lo menos`,
  `It lacks | Carece`,
  `In spite of the fact that... | A pesar del hecho de que...`,
  `at a glance... | De un vistazo`,
  `bump into it | Chocar con eso`,
  `gather together | Reúnanse`,
  `We'll circle back | Daremos la vuelta`,
  `Mark is the least intelligent of my friends`,
  `I want to go to the least dangerous place in the city`,
  `Let's focus on the least difficult problems first`,
  `Angela is the least pretty of them all`,
  `Without further ado | Sin más preámbulos`,
  `She plays late (she interpretes to anyone else)`,
  `Fine, have it your own way | Hazlo a tu manera`,
  `Go past the bakery and the café is on your left | We can use "past" to indicate movement beyond a certain point`,
  `More formal: The bus stop beside the bank; Less formal: The bus stop is next to the bank
    | The prepositions "beside" and "next to" both mean __by the side of something or someone__`,
  `You can tell from his stance he's still aggressive dominant | Se puede decir por su postura que sigue siendo agresivo y dominante`,
  `Seeking revenge | Buscando venganza`,
  `Meantime, let's ponder the crooke's motive | ... reflexionemos sobre el motivo del ladron`,
  `no wonder you fell for that crook's phony promises | No es de extrañar que cayeraas en las falsas promesas de ese ladron`,
  `Out of the question! | Fuera de toda duda!`,
  `My flight doesn't leave until 11pm`,
  `I often spend time with my friends, It will be nice to spend some time together`,
  `I'm sorry I screed up | Siendo haber metido la pata`,
  `Plus 30 degrees fharenheit and rising | Mas 30 grados fahrenheit y subiendo`,
  `So far, so good | Hasta ahora, todo bien`,
  `Verb patterns involve two verbs: a __stative__ verb that refers to a state of mind, and an __action__ verb
    | Stative verbs: to want to ..., to like to..., to decide to..., to hope to... to plan to..., to try to...`,
  `You have never cared about my career | Nunca te ha preocupado mi carrera`,
  `Have they worked at all | ¿Ellos han trabajado?`,
  `Has no one informed her? | ¿Nadie la ha informado?`,
  `How long have you lived here? | ¿Cuánto tiempo has vivido aquí?`,
  `Where have you worked before? | ¿Dónde has trabajado antes?`,
  `Who has helped you this week? | ¿Quién te ha ayudado?`,
  `Why have you not called them ,  Why haven't you called them?`,
  `Shut your filthy mouth | Cierre tu asquerosa boca`,
  `The world is a filthy place | El mundo es un lugar asqueroso`,
  `Our budget turned out to be smaller than we had thought | Nuestro presupuesto resultó ser menor de lo que habíamos pensado`,
  `My bag feels lighter today than yesterday | Mi bolsa se siente más ligera hoy que ayer`,
  `I'm not sure if I'm going to be able to make it | No estoy seguro de si voy a poder hacerlo`,
  `I'm sorry I didn't get to see you | Siendo haber perdido la oportunidad de verte`,
  `Why do I have to pull the heavier suitcase | ¿Por qué tengo que llevar la maleta más pesada?`,
  `Then again, It's nicer to have to much to read than too little | Por otra parte, es mejor tener muchos libros para leer que pocos`,
  `But still, next time I'm going to choose the suitcase that's smaller | Aún así, la próxima vez que voy elegiré la maleta que sea más pequeña`,
  `This is the slowest line I have ever waited in | Esta es la fila más lenta en la que jamás he esperado`,
  `A two hour delay was a bit too much for her`,
  `Which gate does the flight leave from?`,
  `We're kind of counting on your autobiography`,
  `Have you got a minute = Gotta minute`,
  `I have got to go = I gotta go`,
  `We gotta get up at five tomorrow`,
  `Shes has got a boyfriend = She's gotta boyfriend`,
  `You hungry? R: kinda = Are you hungry? R: kind of | mas o menos`,
  `I'm kinda worried, tired, thirsty | Estoy un poco preucupado, cansado, con sed`,
  `You should have asked = You shoulda asked`,
  `I would have helped you = I woulda helped you`,
  `Let me thing about it = Lemme thing about it`,
  `Could you give me a hand? = Could ya gimme a hand?`,
  `Whaddya = what do you, what are you`,
  `What are you going to do this weekend? = Whaddya gonna do this weekend?`,
  `What do you want to have for dinner? = Whaddya wanna have for dinner?`,
  `What do you have to do before work = Whaddya hafta do before work?`,
  `I hafta go to the bank, I gotta go to the bank`,
  `You haven't shared the document with us yet, have you?`,
  `My friends and I went on a road trip to ...`,
  `We planned everything in advance`,
  `On the way there, we went sightseeing in Las Vegas | De camino, hicimos turismo pro Las Vegas`,
  `I've been in a good mood lately | He estado de buen humor recientemente`,
  `He has given me so much of his time | Ha invertido mucho tiempo en mí`,
  `Social workers face many challenges nowadays | Hoy en dia, los trabajadores sociales se enfrentan a muchos desafíos`,
  `Go on an adventure`,
  `good time management skills`,
  `I may take the whole army single-handed | Puede que me lleve a todo el ejercito sin ayuda`,
  `I was heading for an island with wild natives | Me dirigía a una isla con nativos salvajes`,
  `There's something wrong with my computer screen`,
  `Did you manage to connect your phone to the wifi?`,
  `Could you give me a hand with this application?`,
  `I could switch fields for a change, too | Yo también cambiaría de sector`,
  `It's getting a bit boring`,
  `I have never worked anywhere else than in the factory`,
  `I've been looking into jobs in my field`,
  `I was mad at Dwight, I did it out of spite | Yo estaba enfadado con Dwight, lo hice por despecho`,
  `You can not go wrong with a throat punch`,
  `I get a headache when I look at the computer screen for too long`,
  `They have thought this through | Lo han pensado detenidamente`,
  `Larry has finally found his calling | ha encontrado su vocación`,
  `Nothing at work has ever brought me as much joy as this project | Nada me ha traido tanto exito en el trabajo como este proyecto`,
  `I told him not to worry about it too much`,
  `We've come to this conclusion`,
  `I came as soon as I heard what had happened`,
  `I spoke to the staff about the upcoming changes yesterday`,
  `I meant what I said | Yo quise decir lo que yo dije`,
  `This is the most exciting workplace I've ever been in`,
  `Not so much anymore`,
  `Me and my friends used to compete to see who could get the most points`,
  `We'll sprinkle some sugar on the table`,
  `Do you wnat to hang out?`,
  `Olivia is getting along well in her studies | Olivia está llevando bien sus estudios`,
  `job duties | Deberes`,
  `He hung up on me! | Me colgó`,
  `get alongo with somebody, get along in something`,
  `When we heard what had happened, we wanted to find out more`,
  `Keep up the good work!`,
  `Take after | Parecerse a`,
  `How are you holding up? | ¿Cómo lo estás sobrellevando?`,
  `I'm looking forward to it | Tengo muchas ganas, Estoy ansioso`,
  `I think you take after your mother. - Yes, we really look alike`,
  `We haven't had a chance to cath up lately | No hemos tenido oportunidad de ponernos al dia últimamente`,
  `Perhaps our gathering tonight will cheer you up | Quizá nuestra reunión de esta noche te anime`,
  `It's going to be great`,
  `My mother brought me up with lots of love | Mi mamá me crió con mucho amor`,
  `Having twins seems to run in the family | Tener gemelos parece que viene de familia`,
  `We have become closer over time | Nos hemos vuelto cercanas con el paso del tiempo`,
  `He always got on very well with his mother-in-law | El siempre se llevó muybien con su suegra`,
  `I am going to stop sleeping around | Voy a dejar de dormir por ahí (with someone)`,
  `He has been my best frind for five years now`,
  `Yesterday I took my stepson to the movies | Ayer llevé a mi hijastro al cine`,
  `I knew I would like this apartment`,
  `You were supposed to be home at six`,
  `We talked for a while`,
  `I thought we could order pizza`,
  `Do you think those two could be having an affair? | Aventura`,
  `What is the key to a happy marriage?`,
  `The staff is at your service`,
  `We want our employees to be happy and motivaded`,
  `Do you know who your ancestors are?`,
  `My roommates are basically just acquaintances to me`,
  `He became an orphan as a toddler`,
  `Those are my godparents with a random acquaintance of theirs`,
  `No, I mean the picture with the two toddlers`,
  `They're my ancestors, although I don't know exactly who they are `,
  `Toddlers should not be left unsupervised on the playground`,
  `My mother told me that being a single parent in the 1920s was tough`,
  `I'm going on a trip around India`,
  `I didn't see him yesterday either | tampoco lo vi ayer`,
  `Have you heard anything from him? | ¿Has sabido algo de el?`,
  `Did he say anything to you? | ¿Te dijo algo?`,
  `I wonder how my cousins are doing`,
  `I didn't call him yesterday even though I promised to`,
  `I haven't seen him in a very long time`,
  `Has she moved to her own place already?`,
  `Your husband does have an amazing sense of humor | This is not a question`,
  `Every Saturday my roommate would come home late | Cada sábado mi compañero de piso solía llegar a casa tarde`,
  `Used to | Se puede usar para hablar tanto de estados como de hábitos pasados`,
  `Would | Solo se puede usar para hablar de hábitos pasados`,
  `She would dress up as her twin to trick the teachers | Ella se vestía como su gemela para engañar a los profesores`,
  `What was your childhood like?`,
  `I would visit the cows every day and I knew all their names | Iba a ver a las vacas...`,
  `Can you make it to my party on Friday? | When someone asks "Can you make it to...?", they are inviting you to an event`,
  `Sure, count me in!`,
  `Thanks for the invite - we're in!; Lucy says "she's in" for your drinks party; Sure, count us in for drinks later; They said to count them in!
    | Two very common informal expressions you can use to accept a party invitation are "I'm in " and "count me in"`,
  `Can I let you know later?`,
  `Why are you always trying to play it cool? | ¿Por qué siempre intentas actuar como si nada?`,
  `Where have you been hiding yourself?`,
  `How long have you been selling ballons?`,
  `How have you been getting away with this? | ¿Cómo te has salido con la tuya?`,
  `Would you like me to bring anything?`,
  `Thank for the dinner invite`,
  `Sorry, I can't make dinner tomorrow, I have other plans`,
  `I'm afraid I can't make it | We can use "I'm afraid" to help us sound more polite when saying no to an invitation`,
  `I can't decide whether this sign should say --- or ---]`,
  `Would you mind fixing both of our wasing machines while you're here?`,
  `Accommodation will probably be the most expensive part of our trip | El alojamiento será...`,
  `I hope you will join us on the excursion`,
  `Will you take care of the travel arrangements? | ¿Te encargarás de los preparativos para el viaje?`,
  `We will confirm the schedule well in advance | Confirmaremos la planificación con bastante antelación`,
  `Rendering you personally liable | Haciéndote personalmente responsable`,
  `It sounds like we've got plenty of food | Plenty means "a large number" or "more than enough"`,
  `I think we've got some, but we'll need a few more...`,
  `Our budget will not be sufficient to stay at a five star hotel | presupuesto`,
  `You won't get to know the local way of life on a package tour`,
  `I'm going to look up flights tonight | Buscar vuelos`,
  `All the hotels are going to be full this time of the year`,
  `Are you going to visit all the countries on your bucket list? | Lista de deseos`,
  `I think we're going to travel more frequently now that the kids are older`,
  `There's no such things as an affordable but fancy hotel`,
  `We made arrangements that ended up being out of our budget range | Hicimos preparativos que terminaron estado fuera de nuestro presupuesto`,
  `The resort we visited was so shabby | El resort que visitamos estaba tan descuidado`,
  `Yes, and it was neither fancy nor all-inclusive`,
  `That's what the brochure said it should have been like | Según el folleto así debería haber sido`,
  `Next time, let's do better research before making travel arrangements`,
  `Fancy restaurants are often very pricey`,
  `With good planning, it is possible to travel even on a small budget`,
  `I chose a standard room over an en-suite because it's cheaper`,
  `She and I will be in Brazil when you get back from your vacation`,
  `We are leaving at four, so pack your things | Nos iremos a las cuatro ...`,
  `Our flight leaves at nine`,
  `I will give you a ride to the airport`,
  `We will arrive on schedule, I promise`,
  `We went on an excursion to see the local attractions`,
  `Bike rentals are a great way to explore places if the rates aren't too high`,
  `Sometimes they have even invited me into their homes`,
  `I'm often amazed by their hospitality`,
  `The room rates should be roughly the same as last year | ... deberíán ser más o menos las mismas ...`,
  `Did you hear already?`,
  `There will be a major delay in the schedule`,
  `Are there any other trips we could participate in?`,	
  `I'm planning to go on another excursion that starts at four`,
  `Would you like to join me?`,
  `Sounds like a plan!`,
  `My parents are throwing me a party | When talking about organising a party we use the phrase "to throw a party"`,
  `The flight should be on schedule`,
  `Most of the attractions there should be quite inexpensive`,
  `For our vacation, we're staying at a five star hotel`,
  `I'm not going to be able to help you with the bookings`,
  `He was calm despite the pressure oh him`,
  `They have had a lovely vacation`,
  `I'm letting it wash over me | []`,
  `I'll just play along | Te seguiré el juego`,
  `Would you like me to bring anything, Can I bring anything?`,
  `Can I take these liquids on board | Onboard escrito todo junto es un adjetivo, como en "onboard entertainment"`,
  `My flight arrived a few minutes ahead of time`,
  `I hope I won't suffer from motion sickness this time`,
  `Let's wait until all the other passengers have left`,
  `The taxi lines were much longer than I had expected`,
  `I don't feel well enough to travel, as I have been throwing`,
  `Which way is the baggage claim?`,
  `This terminal is easily the most modern one I've ever seen`,
  `That is to say through extorsion or threats | Es decir, mediante extorsión o amenazas`,
  `Make no mistake | Pero no se equivoque`,
  `I hope you're feeling hungry because dinner's ready`,
  `Dig in before it gets cold!, Just help yourself. There's plenty of everything
    | At the dinner table, "help yourself" means that we can start putting food on our plates and we do not have to wait for anyone to serve us.
    We can also say "dig in" which is more informal`,
  `Your glass is empty, can I top it up for you? | "To top up" as a verb as well as a noun: "a top-up"`,
  `Can I top your glass up?, Let me top up your wine glass, Would anyone like a top-up?
    | We use the phrase "Would you like a top-up" or "Can I top you up?" to offer a guest some more drink`,
  `Would you like seconds? | Offering more food`,
  `Do you want a top-up? | Offering more drink`,
  `The earth looks more beautiful when you're in the air`,
  `This is the most chaotic airport I've ever been to`,
  `Her story was more relatable to me | Me identifiqué mas con su historia`,
  `This is the most dangerous part of this city`,
  `She is th emost careless of us three`,
  `That flight took longer than I expected`,
  `These passengers are more demanding than those that we had yesterday`,
  `I've dealt with very difficult pasengers lately`,
  `But the man today was the most challenging one of them all`,
  `He kept on yelling at us with the most annoying voice`,
  `I'm sure he would've just kept on getting more furious`,
  `Direct flights are nicer than those with changes`,
  `I am more helpless in a big airport than my sister is`,
  `Our gate is further away than theirs, Our gate is the furthest one`,
  `How long is the stopover? - Only half an hour - Ok, we'll run as fast as we can`,
  `Let's hope the food isn't absolutely awful`,
  `It is so much less stressful to travel with just a carry-on than with big suitcase`,
  `We have to be extremely quick so that we won't miss our flight`,
  `Your suitcase is far heavier than what is allowed
    | El adverbio "far" tiene un significado más fuerte que "much", far heavier = very much heavier`,
  `I don't feel well enough to travel, as I have been throwing up`,
  `He might be tired enough to be able to sleep on the plane`,
  `Yes!, I did so online, It's much more convenient - I bet, What about our passports?`,
  `They used to be valid for a much longer period of time`,
  `How ususual that they're starting boarding on time`,
  `This airline is hardly ever behind schedule, It's easily the most reliable one | Esta aerolinea casi nunca va con retrado...`,
  `I have to start flying with them more often`,
  `They are suitable for a long time`,
  `Who have a much tighter schedule than us?`,
  `He stood on one leg for three minutes before he lost his balance`,
  `She held my hand`,
  `He has stood in the exact same spot for a ling time now | Lleva mucho tiempo parado en el mismo sitio`,
  `You are holding it in your hand`,
  `It's pouring outside - Yes, it's raining quite a lot`,
  `I don't like mud, but unfortunately my dog does`,
  `I loved jumping in puddles as a kid | charcos`,
  `I wish we had some colder days, I can't stand this heat`,
  `The fog makes it difficult to see far ahead`,
  `In the summer, a cool breeze is more than welcome`,
  `And incidentally, you look every inch a queen | Y por cierto, pareces toda una reina`,
  `head back | Regresarse`,
  `They've already headed back to the hotel`,
  `I bet you have experienced exciting moments during this tip`,
  `We'll be arriving at my place in about ten minutes`,
  `They have forecast a thunderstorm for this weekend`,
  `Don't you think it's freezing cold out there?`,
  `My flowers have frozen due to the cold weather | freeze - froze - frozen`,
  `It's rather chilly in here | Está bastante fresquito acá`,
  `Tim has kept it a secret for over ten years already`,
  `We keep our glasses in that cupboard | Guardamos nuestros vasos en esa alacena`,
  `That book has lain on that table for days now`,
  `She has lain in bed for hours`,
  `That woolly hat would match nicely with your gloves`,
  `Bring your waterproof jacket, it's going to rain in the evening`,
  `Do you remember when he fell off his bike and broke his leg?`,
  `Do you wanna go back out there? | volver a salir`,
  `How hot is this plate?, How cold does Paris get in the winter? | We can use "How" + adjective to ask someone for more detailed information`,
  `How hot does it get where you live?`,
  `How hard was it for you to learh English?`,
  `How long have you lived in this city?`,
  `How far is your house from the center of town?`,
  `How often do you see your parents?`,
  `How long did you spend cooking? | ¿Cuánto tiempo pasaste cocinando?`,
  `How long have you lived in this city?`,
  `It's such a windy day today, isn't it?`,
  `She isn't going to jog with us, is she?
    | Una question tag está formada por un verbo auxiliar (be, have, do o un modal) y un pronombre sujeto (I, she,...) o el sujeto there`,
  `Mark is staying at home today, isn't he? | No olvidar conjugar el verbo de acuerdo a la persona y al tiempo gramatical de la oración principal`,
  `This is a extremely cozy bedroom, isn't it? | Si la oración es positiva, la question tag será negativa`,
  `The weather isn't going to get much better today, is it? | Si la oración es negativa, la question tag será positiva`,
  `That jacked isn't really warm, is it?`,
  `We are staying indoors today, aren't we?`,
  `There were a lot of puddles outside, weren't there?`,
  `There weren't any public restrooms available, were there?`,
  `They haven't been wearing layers even though it's windy, have they?`,
  `You couldn't see I was weaving at you, could you?
    | Si en la oración hay un verbo modal (must, will, should, would, can, could) la question tag tendrá el mismo verbo modal`,
  `My throat is so sore, I feel sick | Me duele la garganta...`,
  `You didn't wear a scarf yesterday, did you?`,
  `I did't even go outdoors - You didn't?, That's odd | ...que raro`,
  `It could still be due to the weather, couldn't it? | De todos modos, podría ser por el clima...`,
  `You forgot to pack your rubber boots, didn't you?
    | Si noy hay un verbo auxiliar en la oración, la question tag estará formada por el verbo DO en su forma correspondiente`,
  `I am using the navigator correctly, aren't I | Si I am aparece en la oración, la question tag será aren't I?`,
  `I am dressed warmly enough, aren't I?`,
  `How may I help you?`,
  `What would you like to have? | ¿Qué le gustaría comer?`,
  `Thank you for ordering from us`,
  `Remember to take the navigator with you as well`,
  `The fog can make it difficult to see far ahead`,
  `My rubber boots are in the truck, aren't they?`,
  `Carol will take good care of the house, won't she?`,
  `People panicked as the fire alarm went off | ...sonó`,
  `We do not know who lit the fire`,
  `Everybody in the office was panicking`,
  `The test cars crashed just as intended`,
  `We'll be arriving at my place in about ten minutes`,
  `Monica fell down on her way to work`,
  `He has grown at least two inches since I last saw him`,
  `We grew lots of herbs in our garden`,
  `Her whole body shook out of fear`,
  `Mike is clumsy and keeps having little accidents all the time | ...es bastante torpe...`,
  `Which brings me to my next invention | Lo que me lleva a mi siguiente invento`,
  `Who are my dessert?, Who ordered this pizza?, Who was eating my dessert?
    | The question word "who" sometimes behaves differently from the others. That's because it can play different roles in a sentence.
    When it's the subject (performing the main verb), "who" goes immediately before the verb and the rest of the question has the same structure as a positive sentence. We don't use "did" + verb in these cases`,
  `Who did you want to invite? | Here "who" is the object and "you" is the subject`,
  `Washing your hands helps prevent illnesses | "help do" and "help to do" are corrects`,
  `The sound of the fire alarm is so loud that you will certainly hear it`,
  `For the sake of safety... | Por motivos de seguridad...`,
  `A bandage helps the wound heal | La venda ayuda a que se cure la herida`,
  `I'm having difficulty breathing | Estoy teniendo difficultades para respirar`,
  `The patient's condition has gotten better now`,
  `Please use goggles for the sake of safety`,
  `He lost a large amount of blood in the accident`,
  `A big crowd of people gathered around the unconscious person`,
  `He was relieved when he saw the light of the emergency exit | Se tranquilizó...`,
  `Your cooking set off the alarm | turn on`,
  `They managed to put out the fire | Ellos consiguieron apagar el fuego`,
  `I asked you to switch the lamp ON, not off`,
  `Who has switched the lamp off? | La mayoría de los phrasal verbs permiten situar el objeto antes o después de la preposición`,
  `I can't believe the alarm went off again | (Turn on) "To go off" también significa explotar o apagarse`,
  `I pulled over to see what had happened | Paré el auto...`,
  `Do you happen to know what set off the smoke detector | ¿Sabes qué disparó el detector de humo?, ¿Sabes por casualidad...?`,
  `Was it your cooking set off the alarm? | ¿Fuiste tu al cocinar...?. To set off también significa "empezar un viaje"`,
  `How would you like it if...? | ¿Que te parecería si ...?`,
  `Let you in on a little secret | Te voy a contar un pequeño secreto`,
  `How many people came to visit you?`,
  `I took me a week to get over my cold | "To get over" can mean to recover from an illness (like a cold)`,
  `I haven't understood anything he has been saying for the past twenty minutes`,
  `I met Stephanie at the café yesterday | Ayer quedé con Stephanie en la cafetería`,
  `We spent like two hours talking there`,
  `We had so much catching up to do | Teniamos mucho que contarnos`,
  `What did you guys talk about?`,
  `This paper won't stick so I need more glue | El papel no se pega...`,
  `The pipe burst | La tubería se rompió`,
  `The glue is non-toxic and can be washed off with water | ...retirarse con agua`, 
  `Perhaps muted color would be better | Tal vez un color apagado sería mejor`,
  `I went with my gut | Me dejé llevar por mi instito`,
  `make them all disappear into thin air | Thin no se traduce`,
  `I have a sore throat`,
  `I have a sore throat from singing too much. I get a headache if I don't drink enough water. I have a pain in my back from working all day
    | We usually use "sore" to describe pain in our throat or muscles. We often use "ache" to talk about pain in our head or muscles. We use "pain in" with any body part`,
  `I have a temperature | We use "to have" when someone is currently experiencing an illness`,
  `I suffer from allergies in the spring | We can use "to suffer from" with an illness or medical condition (like allergies)`,
  `I have a horrible cold at the moment`,
  `I think I've picked up a bug at school
    | "to pick up a bug" is an informal way of saying "to catch a minor illness. It can also be used to describe the moment someone becomes ill, tipycally when an illness is caught in a public place or through casual contact"`,
  `He caught the flu last month, it lasted for two weeks | We can use "to catch" to describe the initial moment or period when someone becomes ill`,
  `I have a sore back`,
  `I suffer from back pain`,
  `I try to use less water in order to be more eco-friendly`,
  `If you purchase disposable cutlery, make sure it is compostable | Si compras cubiertos desechables, asegurate de que sean compostables`,
  `Don't step on the broken glass`,
  `Honestly is an admirable quality in a person
    | La mayoría de los sustantivos abstractos son incontables. En inglés "the" no se usa con sustantivos incontables o plurales para hablar de cosas en general`,
  `Will there ever be peace in the world? | ¿Habrá alguna vez paz en el mundo?`,
  `Did you already let the dog out today?`,
  `Our old couch felt more comfortable`,
  `My sister cur her favorite doll's hair and regrets it now | ...cortó el pelo de su muñeca favorita y ahora se arrepiente`,
  `I have never felt this way before`,
  `She began to write her first book yesterday | Ayer comenzó a escribir su primer libro`,
  `It is one of the most imprtant things I own`,
  `Devices like laptops and phones are such important parts of our lives now`,
  `I got my laptop a couple years ago`,
  `I can bring my laptop with me`,
  `I need to see a doctor about my cough`,
  `I'll make an appointment with the doctor tomorrow`,
  `I'm having the lasagna`,
  `But we always deal with them fairly too | Pero siempre nos ocupamos de ellos de forma justa también`,
  `I can't help thinking of only myself | No puedo evitar pensar solo en mí`,
  `The thought of D being exposed | La idea de que D sea expuesto`,
  `The doctor said to get some rest to recover faster`,
  `It's important to eat well to stay healthy`,
  `You need to keep away from alcohol while taking this medication`,
  `My mother told me to steer clear of smoking | We can use "to steer clear of" to talk about avoiding something because it's harmful`,
  `He tries to avoid going out in the cold | We can use "to avoid" for general advice on avoiding substances, activities or conditions that can be harmful to our health`,
  `I need to keep away from cats because I'm allergic | We often use "to keep away from" with physical things that can cause us harm`,
  `After surgery, you should steer clear of heavy lifting | We use "to steer clear of" to give a stronger warning or to emphasise the importance of avoiding something`,
  `She needs to avoid eating too much sugar`,
  `I got laid off, and now I'm not sure how we can afford our mortgage payments`,
  `This apartment is worth more than you can afford, I'm afraid | Me temo que...`, 
  `In ten years they will be worth twice as much | ...vandrán el doble`,
  `Let's hope so | Esperemos que si`,
  `We just found out that a major investor wants to invest in our company | Acabamos de saber que un gran inversor...`,
  `He sold the shares of his family company at a good profit | ...a un buen precio`,
  `This painting is worth hundres of dollars | Esta pintura vale ...`,
  `Net income is also called take-home pay`,
  `After years of careful budgeting, we finalyy paid off our mortgage |...administrar los ahorros...`,
  `Gross income is the amount of money you earn before any taxes or other deductions`,
  `Let's go grab some burgers before the game | Vayamos por unas ...`,
  `Carl almost choked on a piece of bread`,
  `It's cool - I forgive you | También se puede decir "I'm cool" or "we're cool" para expresar que no hay problemas por resolver`,
  `She's got to be kidding | Tiene que estar bromeando`,
  `Did you hear about the position through a job advertisement or through networking?`,
  `I just need to fill in an application form on the company webiste and send them my resume`,
  `I even have all the necessary qualifications for it`,
  `She has countless interests | Tiene incontables intereses`,
  `She has been trying to fill in the application form for over an hour`,
  `As the company grows, it will become necessary to recruit new people`,
  `We need to employ more workers to achieve our goals`,
  `She started as a trainee before starting in her current position`,
  `It can seem impossible to find information about internships relevant to your career goals`,
  `He used a lot of time to educate himself about different career options`,
  `I tried to plan my career path carefully before ending up in my current position`,
  `I made sure I got an education that is relevant for my career goals`,
  `To gain experience in my field`,
  `Things never go as planned, so many things happened that I couldn't prepare for`,
  `It is compulsory to protect your clothes in a laboratory | Es obligatorio...`,
  `Are you going to fill in the application today?`,
  `I have the qualifications that meet the requirements of the job description | Tengo las cualificaciones que cumplen...`,
  `I'm not going to make this decision for you`,
  `A good education doesn't guarantee happiness`,
  `Breathe in and out`,
  `It hurts my chest every time I breathe in`,
  `Why should we hire you?`,
  `Tell me about a challenge you've faced at work and how you handled it`,
  `What are your strengths and weaknesses?`,
  `I have a job interview coming up next week`,
  `It seems like a good opportunity and I really want them to hire me`,
  `She knows I can take on any challenge | Sabe que puedo enfrentar cualquier reto`,
  `This open position looks like it could be for you`,
  `I'm concerned that I don't have enough references | ...me preocupa...`,
  `He was totally unprepared for the interview`,
  `The former trainee was quite inexperienced | el aprendiz anterior...`,
  `It's impossible to be young and also have a lot of experience`,
  `I'm afraid I'm too inexperienced for this position | Me temo que ...`,
  `yeah, I don't think we can do it either | ...yo tampoco creo que...`,
  `I'm impatiently waiting for the exam results`,
  `I tried to, but I still feel unprepared`,
  `I'm also afraid that I'm too inexperienced for this job after all`,
  `I'm sure that's not the case since you've already made it this far | ...ya que has llegado tan lejos`,
  `On no, you're worrying too much`,
  `I want to return this shirt because doesn't fit me`,
  `I got into the university | Entré a la universidad`,
  `You have to pay your tuition fee as you enroll at the university`,
  `Oh I see. It's taking pretty long, isn't it?`,
  `I think she's getting a bit impatient already | Creo ya se está volviendo un poco impaciente`,
  `Let's hope that the results arrive soon then`,
  `Jamie's friend decided to defer his entry for a year | decidió aplazar su ingreso por un año`,
  `I'm worried I won't be able to pay my tuition fee | Me preocupa no poder pagar...`,
  `He plans to enter a university abroad | Planea entrar en una universidad extranjera`,
  `Maybe somebody will help him make a choice`, 
  `Lauren was overjoyed when she hot her acceptance letter | Lauren estaba llena de alegria cuando...`,
  `Does the applicant meet all the requirements? | ¿Cumple con todas los...`,
  `Employ - employer - employee; interview - interviewer - interviewee; train - trainer - trainee; advise - adviser - advisee;`,
  `Is your former employer going to be there? | ¿Va a estar allí tu antiguo jefe?`,
  `We are going to have a meeting today about development ideas regarding our ways of working | ...para el desarrollo de ideas sobre nuestra forma de trabajar`,
  `Is everyone required to participate?`,
  `The new requirements will concern both the employer and the employees, so everyone should be there, even the trainees`,
  `He is entering university next fall | El entrará a la universidad el proximo otoño`,
  `There is this one very interesting company that is hiring at the moment and I just happened to see ther add`,
  `The texture of this meal makes it easy to swallow | La textura de este plato hace que sea fácil de tragar`,
  `He swallowed the rest of his beer in one gulp`,
  `You need to chew carefully before swallowing`,
  `You shouldn't talk while chewing your food`,
  `We're having meatloaf for dinner tonight`,
  `That friend of Anne's is always so cheerful
    | El doble genitivo se usa cuando la palabra principal está precedida por un artículo indefinido, un pronombre (this, that) o un número`,
  `The man by the wooden counter is a former teacher of mine | El doble genitivo también se puede usar con la preposición "of" y un pronombre posesivo`,
  `That cousin of yours ordered drinks for us all`,
  `That's the only shirt of your sister's that I like`,
  `That Jack is a friend of our family's`,
  `That girl over there is a colleague of my sister's`,
  `A colleague of Peter's waved at us`,
  `In spite of its bitter taste, Julia really likes gin | Las expresiones "in spite of" y "despite" se usan para indicar contraste. Van seguidas de un sustantivo, pronombre o verbon en -ing`,
  `In spite of it being crowded, we went into the bar anyways`,
  `Despite me wanting my steak rare, it was served medium | Despite no lleva preposiciones`,
  `Despite the unusual texture, this pastry is really good`,
  `In spite of being tired, they wanted to celebrate more`,
  `Although he was drunk, he ordered more drinks | También puedes usar "although" para indicar contraste. Pero a diferencia, va seguido del sujeto y del verbo principal`,
  `Although he was careful, he still spilled his drink | ...se le derraó la bebida`,
  `Despite the weather, I'd like to go out for a while`,
  `I'm sure we'll have fun, although we're goung to get really wet`,
  `They really wanted to sit outside, despite the bad weather`,
  `Are we all going to fit on this bench? | ¿Vamos a caber todos en esta banca?`,
  `I suppose we could borrow a few stools from over there | ...tomar prestados algunos taburetes de allá`,
  `I would rather drink lager than ale | Would se usa con Rather para indicar una preferencia`,
  `You shouldn't swallow your food without chewing`,
  `I'm craving chocolate | Tengo antojo de chocolate`,
  `Wouldn't you like something savory instead?`,
  `Shouldn't you at least try it?`,
  `Teaching manners | Enseñando modales`,
  `I always politely remind my friends about proper table manners when we are eating out | Siempre les recuerdo amablemente...`,
  `Wouldn't you like to wait for everyone to get their food before you start to eat?`,
  `Shouldn't you finish chewing before you talk?`,
  `I don't suppose you could pass the bread when you're done? | ¿Podrías pasar el pan cuando hayas terminado?`,
  `My friends keep asking me whether I would rather just eat my myself | ...sighen preguntándomme si prefiero comer solo` ,
  `I fell head over heels | Caí de cabeza`,
  `I didn't get dressed up for the firemen | No me arreglé para los bomberos`,
  `Have you thought about quitting smoking?`,
  `Why don't you cut back on meat? | Reducir el consumo`,
  `Have you tried eating more vitamins?`,
  `Have you thought about seeing a doctor?`,
  `Have you tried restarting your computer?`,
  `I'm taking him home since he's too drunk to drive`,
  `Be careful not to spill your drink | Derramar`,
  `Some music and lights could really liven up the atmosphere`,
  `How about sharing a pitcher of strawberry margarita? | ¿Qué tal si compartimos una jarra...?`,
  `It's customary to leavy a tip for service | Es habitual dejar propina...`,
  `Mario spilled some of his drink on my shirt`,
  `So this guy walks into a bar... | ...entra al bar...`,
  `I'm in this exam and then my phone starts ringing | El presente simple también se usa para contar una anectoda`,
  `The main character spends a summer abroad | El presente simple también se usa para describir una trama`,
  `I met a Turk, two Poles and a Spaniard during my exchange year | año de intercambio`,
  `It's a shame I don't speak any Turkish, Polish or Spanish | Lastima que...`,
  `We overcame the language barrier by using body language | Superamos la barrera de idioma...`,
  `Hay cuatro tipos de condicionales en inglés: cero, primer, segundo y tercer condicional`,
  `Plants dry up if you don't water them
    | Se secan. Condicional cero, se utilizar para hablar de hechos reales o de situaciones que siempre suceden como consecuencia de una determinada condición`,
  `If it's a nice day today, we'll go to the beach | Condicion 1: expresa qué ocurrirá si se cumple la condición`,
  `If I was a superhero, I would fly over the mountains
    | Condicional 2: Expresa condiciones hipotéticas del presente o del futuro que son muy poco probables o imposibles de ocurrir. Cuando el verbo principal de la cláusula con if es "be", es posible utilizar tanto "were" como "was" con I y he/she/it. Con otros pronombres personales se usa siempre la forma "were"`,
  `If the beach was closer, I would go there every day | Condicional 2: Compuesto por una cláusula subordinada con "if" que representa la hipótesis, y por una cláusula principal que describe qué ocurrirá si se cumple la hipótesis`,
  `He would come if he was feeling better | Condicional 2: La clausula subordinada se forma con "if" + pasado simplre. La clausula principal se forma con "would" + verbo en infinitivo. El orden de ambas cláusulas es indiferente`,
  `We would go camping if the weather was warmer`,
  `If I had enough money, I would travel around the world | Condicional 2`,
  `If we were younger, we would have more time for hobbiery | Condicional 2`,
  `I would buy some candy if the shop was still open`,
  `I should mind my own business? | ¿Debería ocuparme de mis propios asuntos?`,
  `It's your funeral | Se usa para decir a alguien que él, y nadie más, tendrá que lidiar con los resultados desagradables de sus propias acciones`,
  `Do you have any recommendations for a sore throat?`,
  `Have you thought about taking any medication?`,
  `Would you miss me if I lived abroad?`,
  `I could buy an island if I won the lottery | En condicional 2, también se puede usar could o might`,
  `If I were a millionaire, I would buy a house in Spain | Si el verbo de la condición es "be", se puede usar "were" y "was" con I y he/she/it`,	
  `If I was a teacher, I wouldn't give any homework`,
  `If I saved more money, I might have enough for a new car next year`,
  `If you were here I wouldn't feel so lonely`,
  `Panda bears are unique to China | ...viven únicamente en China`,
  `Some stereotypes can be really harmful`,
  `French people aren't all like that, it's just a silly stereotype | ...es un estereotipo absurdo`,
  `I can already see the skyscrapers from the airplane window | Ya puedo ver los rascacielos...`,
  `The best way to get to the city is by public transport`,
  `The entry fee was quite inexpensive | La entrada fue bastante barata`,
  `I might rent a scooter | Quizá rente una motoneta`,
  `Don't go too close to the bonfire | No te acerques mucho a la fogata`,
  `She gets freckles from the sun | Le salen pecas por el sol`,
  `She is such a beauty | Ella es toda una belleza`,
  `She has these cure freckles all over her face | pecas`,
  `I really love those little wrinkles around her eyes that appear when she smiles`,
  `Watch out, that box is really heavy | We can use the imperative "watch out" to give a warning`,
  `It takes a while to get used to wearing braces | Lleva untiempo acostumbrarse...`,
  `She always catches people's attention | ...siempre llama la atención...`,
  `I can't stop staring at him | No puedo dejar de mirarle`,
  `That guy over there has been staring at you all night`,
  `I don't stand a chance, She is catching everyone's attention | No tengo oportunidad, ...`,
  `I cannot resist her charm | ...encanto`,
  `He knelt down and proposed to me | kneel - knelt - knelt`,
  `Both the bride and the groom looked stunning | Tanto la novia como el novio se veían guasones`,
  `He is kneeling! Do you think he's about to propose?`,
  `My parents filed for divorce after years of disagreement | ...pidieron el divorcio..`,
  `Would you like me to walk you home? | ¿Quieres que te acompañe a casa?`,
  `Can I walk you home? | ¿Puedo acompañárte a casa?`,
  `you will meet someone when you least expect it`,
  `but I would brag if I were you | pero yo presumiría si fuera tu`,
  `I hardly studied for the test | Apenas estudié...`,
  `Lately he has been going to bed at 10 p.m. `,
  `I've read nearly every book on that shelf | He leído casi todos los libros...`,
  `Jack truly cares about Rosanna | Jack realmente se preocupa por Rosanna`,
  `I've hardly studied this week, so I need to work hard today`,
  `I hardly even know him | Apenas lo conozco`,
  `She wrote her essay very skillfully | Los adverbios de modo responden a la pregunta ¿Cómo?`,
  `I personally think she's very open-minded | Si hay más de un adverbio en una oración, su orden será: modo-lugar-tiempo`,
  `Can we meet there now? | ¿Podemos vernos allí ahora?`,
  `Weren't you supposed to back up these files?`,
  `Why has she bookmarked this page?`,
  `Simon is drinking coffee while updating his computer`,
  `We will surely solve this issue in the end`,
  `You'll sing the anthem, get your mind off of it | ...para que te olvides de el`,
  `Why don't you stick to singing and your little dance moves? | ¿Por qué no te limitas a cantar y a tus pequeños movimientos de baile?`,
  `The minute I hear I have to perform, I get a huge knot in my stomach | En cuanto oigo que tengo que actuar, se me hace un enorme nudo en el estómago`,
  `This website is super confusing`,
  `I only have five percent battery left`,
  `There is so much information that it only confuses him`,
  `The decision will affect five percent of the population`,
  `This printer won't ever be functional again`,
  `What percentage of the visitors end up buying something from our website?`,
  `As the company grows, it will become necessary to recruit new people`,
  `You need to fill in this field`,
  `My internet connection seems to be a bit unstable`,
  `I bought an e-book but it seems that I'm not able to read it`,
  `I'm wondering whether it's because of my bad internet connection or could this be a server error or something`,
  `The sun has already risen and so should you | ...y tu también deberíás`,
  `He rose to his feet as soon as he heard the doorbell | Se levantó en cuanto escuchó el timbre`,
  `Don't spill coffee on the keyboard | No derrames café...`,
  `Where does this cable go?`,
  `I couldn't save the form because I went over the word count | ...porque superaba el límite de palabras`,
  `You can also search the library database by keywords`,
  `I was thinking about going outside to make out... Care to join me? | besarnos...¿Qué dices?`,
  `Does all this information confuse you?`,
  `Luckily I didn't spill all of it`,
  `Did you spill your coffee again?`,
  `He'll never stop coming for you | Nunca dejará de ir por ti`,
  `Some verbs lke "try", "consider", "avoid" and "suggest", as well as prepositions like "about", typically require the following verb to be an "ing" form`,
  `Have you thought about learning how to swim?`,
  `He fixed the computer quiently downstairs during the night | Orden: sujeto-verbo-objeto-modo-lugar-tiempo`,
  `We met briefly at the cafeteria today | Nos reunimos brevemente en la cafetería hoy`,
  `Have you searched for it in the kitchen? | Lo has buscado en la cocina?`,
  `We can't wait for you any longer, we have to go now | no podemos esperarte mas...`,
  `He finally introduced me to his mother`,
  `I don't have time to attend all those lectures | No tengo tiempo para asistir a todas esas clases (Attend no necesita preposición)`,
  `You have too many lectures to attend`,
  `Two of Sasndra's lectures are overlapping, but she wants to attend both of them`,
  `The professor was a bit absent-minded | El profesor estaba un poco distraído`,
  `Can I borrow these three books? | Lend y Borrow tienen significados diferentes. Lend significa "prestar algo a alguien" y Borrow significa "tomar/pedir prestado algo a alguien"`,	
  `Jacob wants to return his loans before the library closes`,
  `I think the article that I printed earlier is not relevant, but this one might be`, 
  `Indeed, it is | De hecho sí`,
  `I have used up my free print quota for this month | He agotado mi cuota...`,
]