const phrases = [
  `Plenty`,
  `Prone`,
  `briefer`,
  `misusing`,
  `instantiated`,
  `Merely`,
  `Likewise`,
  `cumbersome`,
  `bloating`,
  `shift the focus`,
  `Furthermore`,
  `Even though`,
  `blew up`,
  `to be fair`,
  `is a bit misleading`,
  `upsetting`,
  `spread blatant untruths`,
  `disregarding`,
  `frankly stated`,
  `spread around`,
  `reiterate`,
  `take a bit of fiddling with ...`,
  `worrisome`,
  `Admittedly`,
  `Easypeasy`,
  `is only viable`,
  `unwieldy`,
  `The reason for this claim seems to be`,
  `skeptical`,
  `if you end up not liking it`,
  `Delving into`,
  `nuances`,
  `widely`,
  `neglected`,
  `last but not least`,
  `sleuthing`,
  `under the hood`,
  `In short term`,
  `It all comes down to ...`,
  `That's as far as it goes`,
  `from the shape`,
  `Whilst`,
  `factually correct`,
  `tailored`,
  `Thus`,
  `add up`,
  `Break down the problem`,
  `We're not aiming or perfect`,
  `thoughful`,
  `curated listicles`,
  `straightforward`,
  `Its dependencies remain unchanged`,
  `leveranging`,
  `do either of the following`,
  `towards`,
  `eagerly`,
  `in eiteher case`,
  `reliably`,
  `entitled`,
  `om a tough spot`,
  `halt`,
  `thoroughly`,
  `thwart`,
  `pesky`,
  `daunting`,
  `lean`,
  `debt`,
  `swiftly`,
  `endeavours`,
  `pinpoint`,
  `fairly strightforward`,
  `behave this way`,
  `vacuously`,
  `pun`,
  `pun intended`,
  `counterintuitive`,
  `Regardless`,
  `to be aware`,
  `beforehand`,
  `strengthened`,
  `idle`,
  `chaining`,
  `ground up`,
  `signpost`,
  `caveats`,
  `What are they to begin with?`,
  `abstract away`,
  `comprehend`,
  `tirelessly`,
  `it's a pity`,
  `unbearable`,
  `off it goes`,
  `you're willing`,
  `It's up to you`,
  `It will kick in`,
  `the stale value`,
  `clear out`,
  `arguably`,
  `tempted (sometimes you might feel tempted to...)`,
  `resilient`,
  `It doesn't end up being rendered`,
  `altogether`,
  `keep an eye out`,
  `very few though`,
  `mandatory`,
  `dust off`,
  `although`,
  `fiddlings`,
  `fiddling around`,
  `kinda`,
  `stay out`,
  `wearing off`,
  `the poison should wear off in 5 minutes`,
  `he was paid off`,
  `go off`,
  `went off`,
  `the gun just went off`,
  `So you get better results for what you're wanting`,
  `what do you fancy...?  // opposite of "hate"`,
  `dance the night away`,
  `taking the law into our own hands`,
  `Want to give it another go?`,
  `I grew up in Ver`,
  `It turns out I do, It surprises`,
  `Do you get on[along] well with your family?`,
  `We see one another at...`,
  `We always fight[another verb] with each other`,
  `How do you know each other?`,
  `They dont see each other often`,
  `They see one another every weekend`,
  `You are so kind`,
  `He is so polite`,
  `Cara's fun | Someone who makes you happy to be around them`,
  `my mom is very funny | Someone woho has a good sense of humour and makes you laugh`,
  `They yielded two key realizations`,
  `But those benefits come with some pretty hefty tradeoffs`,
  `tackle`,
  `without relyng on`,
  `crowd`,
  `you have no clue`,
  `stay sane`,
  `Despite`,
  `The job hunt`,
  `Struggle`,
  `Stale React component state (previous state, i think so...)`,
  `We can get rid of some of that cruft by...`,
  `flawed`,
  `move around`,
  `Ruthlessly`,
  `negligible`,
  `jitter`,
  `arose from`,
  `this change shoved off another...`,
  `can seem a bit daunting...`,
  `happen off`,
  `who paved the way`,
  `Stockpile`,
  `brittle`,
  `wind up`,
  `It all boils down to...`,
  `to wander `,
  `to haunt you`,
  `trip each other up`,
  `can be reasoned about`,
  `outcomes predicted`,
  `we get way better...`,
  `the market is tough`,
  `come off`,
  `upbeat`,
  `pump yourself up`,
  `highest bidder`,
  `regarding the...`,
  `Companies are biased towaed hiring people with right attitude`,
  `strive`,
  `thorough`,
  `drifted away from...`,
  `blissful`,
  `spite`,
  `tongue 'n'heek stab`,
  `where can I find the fitting room?`,
  `Their shoes don't match their dresses or bags, but it suits them!`,
  `It loked really in style and matched my brown skirt!`,
  `The fitting room's at the end of the shop on the right`,
  `Pure functions are functions which obey two laws`,
  `The fundamental building block we build our applications with`,
  `How would you like to ...`,
  `That's a reasonable price for those shoes`,
  `That word "reasonable" describes an item that is neither cheap nor expensive`,
  `The designer store has a sale on, so prices are more reasonable`,
  `This traffic is the worst I've seen yet, I'd better...`,
  `Would you like a receipt emailed to you?`,
  `Dou you want me to print or email the receipt?`,
  `And the real you made fun of my pie suit`,
  `The word "crowded" can mean that there are a lot of people or too many people in one place`,
  `The school's sports day is held at a large vanue`,
  `life out here is very different than life in the city`,
  `I am getting better at (it)`,
  `Around the corner = very close (place)`,
  `There's a new cafe on the way to the university`,
  `She passes a post office whilst travelling to work`,
  `the supermarket us just down the street from my apartment`,
  `I'll get breakfast on the way to work`,
  `the pharmacy is on the other side of the shopping centre`,
  `My parents live ON Quenn Street`,
  `Have you come across any nice places to eat here?`,
  `"to come across" menas to find something by change`,
  `Sometimes we come across something by change`,
  `Sometimes an especially nice place is not very well known, we can call these places "finds" or "hidden gems"`,
  `What a great find`,
  `Have you tried that new restaurant yet?`,
  `There's a supermarket just down the road from my apartment`,
  `Around the corner from my house is a really nice place..s`,
  `He owes us an appetiazer`,
  `Thanks fot that severance check`,
  `He used his severance money to start a ...`,
  `that i have some concerns`,
  `What i'm getting at, ...`,
  `my train was delayed by 30 minutes`,
  `Am I able to get a refund?`,
  `We are sorry to announce...`,
  `We are sorry for any incovenience...this may cause`,
  `...has been cancelled due to technical issues...`,
  `We are arranging a replacement bus service for ...`,
  `To go away fot the weekend.`,
  `I think we'll eat lots of local food at the supermarket`,
  `the workflow here is pretty straightforward`,
  `eaversdropping`,
  `He delves into the ...`,
  `This seemingly simple action lies a ...`,
  `with seamless integration...`,
  `By the time you finish...`,
  `A dead giveaway that a function is inpure...`,
  `It was suddenly all the rage.`,
  `If a function were to mutate a property...`,
  `which could screw up something`,
  `throughout your career`,
  `take pride in your work`,
  `be willing to learn`,
  `We decided to go away to XXx this weekend`,
  `We arraive at 10pm, if our flights aren't delayed`,
  `do you want me to quickly summarize for you?`,
  `step towards`,
  `It gets wiped out in memory (erased from memory)`,
  `Conversely (in another hand)`,
  `It's important not to confuse`,
  `We like to go on holiday in the summer`,
  `slight differences`,
  `to go on a cruise`,
  `We can use "to go" to suggest travelling and enganging in an activity.`,
  `We use "to go on" for a specific type of journey, especially an organised event`,
  `The phrase "to go to" indicates moving towards a particular destination`,
  `She wants to go camping`,
  `He doesn't want to go on a cruise`,
  `The love to go to the beach`,
  `I'd wager that's some sort of a code...`,
  `you may yet meet your match`,
  `Would that be some sort of defense against...`,
  `subtle change (b is silent)`,
  `for the job and hand`,
  `tangled up`,
  `mingling data`,
  `if the user screw up.. (make a mistake)`,
  `stale data`,
  `It's a lot more clear what's going on`,
  `rest assured`,
  `they can really add up`,
  `dodged`,
  `worth a gist`,
  `Which you've just seen an example of`,
  `everything is as it should be`,
  `Scratch the surface`,
  `At the very list`,
  `It lacks`,
  `In spite of the fact that...`,
  `at a glance...`,
  `bump into it`,
  `gather together`,
  `We'll circle back`,
  `Mark is the least intelligent of my friends`,
  `I want to go to the least dangerous place in the city`,
  `Let's focus on the least difficult problems first`,
  `Angela is the least pretty of them all`,
  `Without further ado`,
  `She plays late (she interpretes to anyone else)`,
]