const phrases = [
  `Years of logging had left the mountains prone to mudslides | Susceptible, vulnerable, liable`,
  `We have a briefer who will be able to go into this in greater detail
    | Tenemos un informante que podrá entrar en esto con mayor detalle`,
  `misusing | Use (something) in the wrong way or for the wrong purpose`,
  `Instantiated | Represen as or by an instance`,
  `Merely | Just, only`,
  `Likewise | In the same way, also`,
  `Cumbersome | Large or heavy and therefore difficult to carry or use; Unwieldy; Uncomfortable; Awkward`,
  `She suffered from abdominal bloating | A swollen state caused by retention of fluid or gas;`,
  `Shift the focus | To change`,
  `Furthermore | In addition, Besides (Used to introduce a fresh consideration in an argument)`,
  `Even though`,
  `blew up | Explotó`,
  `to be fair | Para ser justo`,
  `It is a bit misleading | Es un poco engañoso`,
  `Upsetting: A painful and upsetting divorce | Causing unhappiness, disappointment, or worry`,
  `Spread blatant untruths | Difundir mentiras flagrantes`,
  `disregarding | Pay no attention to; ignore; Sin tener en cuenta`,
  `frankly stated | Francamente dicho`,
  `spread around | Diseminar`,
  `reiterate | Say something again or a number of times`,
  `take a bit of fiddling with ... | Requiere un poco de manipulación`,
  `worrisome | Inquietante`,
  `Admittedly | Used to introduce a concession or recognition that something is true or is the case; Cierto es que...`,
  `It is only viable`,
  `unwieldy | Difficult to carry or move because of its size, shape or weight`,
  `The reason for this claim seems to be | La razón de esta afirmación parece ser`,
  `skeptical`,
  `if you end up not liking it | Si al final no lo vinculas`,
  `Delving into | Profundizar`,
  `nuances | A subtle difference in or shade or meaning, expression, or sound; Matices`,
  `widely | Ampliamente`,
  `neglected: some severely neglected children; A neglected area of research | Suffering a lack of proper care`,
  `last but not least | Último pero no menos importante`,
  `sleuthing | Careful investigation into a crime or mystery`,
  `under the hood`,
  `In short term | A corto plazo`,
  `It all comes down to ... | Todo se reduce a...`,
  `That's as far as it goes | Eso es lo más lejos que llega`,
  `from the shape`,
  `in the shape of something: Luckily, help arrived in the shape of a police officer | In the form of something, or appearing as something`,
  `Whilst | Mientras que`,
  `factually correct | Facticamente correcta; With regard to what is actually the case, in relation to fact`,
  `tailored | A medida (of clothes) smart, fitted, and well cut`,
  `Thus | As a result or consequence of this; therefore: De este modo`,
  `add up | Agregar, tener sentido, calcular`,
  `Break down the problem`,
  `We're not aiming or perfect`,
  `thoughtful | Considerado`,
  `curated listicles | Listas seleccionadas`,
  `straightforward: A straightforward young man; In a straightforward case no fees will be charged
    | Uncomplicated and easy to do or understand; Directo: Un joven sencillo`,
  `Its dependencies remain unchanged | ...permanecen sin cambios`,
  `leverage: The organization needs to leverage its key resources | use (something) to maximum advantage`,
  `do either of the following | Hacer cualquiera de las siguientes...`,
  `towards | hacia...`,
  `eagerly: Fans of the show are eagerly awaiting the new season | Used to emphasize a strong desire to do or have something`,
  `in eiteher case | En cualquier caso`,
  `reliably | Consistently good in quality or performance; able to be trusted`,
  `entitled | Believing oneself to be inherently deserving of privileges or special treatment (Con Derecho)`,
  `a tough spot | Situación dificil`,
  `halt: A halt in production; There is growing pressure to halt the blodshed | Bring or come to an abrupt stop`,
  `thoroughly: I thoroughly enjoyed the day; He searched the house thoroughly | In an thorough manner; Very much; greatly (Minuciosamente)`,
  `thwart | Prevent (someone) from accomplishing something (Frustrar)`,
  `pesky | damn; fucking (maldito)`,
  `daunting | Seeming difficult to deal with in anticipation (desalentador)`,
  `lean:  | Be in or move into a sloping position (inclinar)`,
  `debt: I paid off my debts | Something, typically money, that is owed or due`,
  `Owed | Have an obligation to pay or repay (something, especially money) in return for something received`,
  `due | Expected at or planned for at a certain time; (Pendiente, Debido)`,
  `swiftly | At high speed; quickly`,
  `endeavours: He is endeavoring to help the Third World; | Try hard to do or achieve something; An attempt to achieve a goal`,
  `pinpoint: One flare had pinpointed the target; | A tiny dot or point; Absolutely precise; to the finest degree; Find or locate exactly`,
  `fairly straightforward | Bastante sencillo(a)`,
  `behave this way`,
  `vacuously | vacíamente`,
  `pun | Make a joke exploiting the different posible meanings of a word`,
  `pun intended | Juego de palabras intencionado`,
  `counterintuitive | Contradictorio`,
  `Regardless | A pesar de todo`,
  `to be aware | Ser conscientes`,
  `beforehand: Rooms must be booked beforehand | antemano`,
  `strengthened | Make or become stronger (Fortificado)`,
  `idle | (Of a person) avoiding work; lazy; Spend time doing nothig (inactivo(a))`,
  `chaining: She chained her bicycle to the railing `,
  `ground up | Molido`,
  `signpost | Señalizar`,
  `caveats: There are a number of caveats which concern the validity of the assessment results
    | A warning or proviso of specific stipulations, conditions, or limitations (advertencia)`,
  `Assessment: The assessment of educational needs | The evaluation or estimation of the nature, quality, or ability of someone or something`,
  `What are they to begin with?`,
  `abstract away`,
  `comprehend | Understand`,
  `tirelessly; Tireless | Incansable; Infatigable`,
  `it's a pity | Es una pena`,
  `unbearable: The heat was getting unbearable | Not able to be endured or tolerated`,
  `off it goes | Se va; Se marcha`,
  `you're willing | Estas dispuesto(a)`,
  `It's up to you | Tu decides`,
  `It will kick in | Se activará`,
  `the stale value | El valor obsoleto`,
  `clear out | Aclarar`,
  `arguably | Posiblemente`,
  `tempted (sometimes you might feel tempted to...)
    | Entice or attempt to entice (someone) to do or acquire something that they find attractive but know to be wrong or not beneficial (Tentado(a))`,
  `Entice | Attract or tempt by offering pleasure or advantage (Atraer)`,
  `resilient`,
  `It doesn't end up being rendered`,
  `altogether | Completely; Totally`,
  `keep an eye out | Estar atento`,
  `though | Aunque`,
  `mandatory: Wearing helmets was made mandatory for cyclists | Required by law or rules; Compulsory`,
  `dust off | Desempolvar`,
  `although | A pesar de`,
  `fiddlings | Jugueteos`,
  `fiddling around | Jugueteando`,
  `kinda | Un poco`,
  `stay out | Quedarse afuera`,
  `wearing off | Desapareciendo`,
  `the poison should wear off in 5 minutes`,
  `he was paid off | Le pagaron`,
  `go off; went off | Follow (seguir)`,
  `the gun just went off | El arma se acaba de disparar`,
  `So you get better results for what you're wanting`,
  `what do you fancy...?  | opposite of "hate"`,
  `dance the night away | all the night`,
  `taking the law into our own hands`,
  `Want to give it another go? | Dar otra oportunidad`,
  `I grew up in Ver`,
  `It turns out I do, It surprises | Resulta que si, es una sorpresa`,
  `Do you get on[along] well with your family? | Get on with ...llevarse bien`,
  `We see one another at... | Nos vemos en ...`,
  `We always fight[another verb] with each other`,
  `How do you know each other?`,
  `They dont see each other often`,
  `They see one another every weekend`,
  `You are so kind`,
  `He is so polite`,
  `Cara's fun | Someone who makes you happy to be around them`,
  `my mom is very funny | Someone woho has a good sense of humour and makes you laugh`,
  `They yielded two key realizations | De ellos se desprenden dos conclusiones clave`,
  `But those benefits come with some pretty hefty tradeoffs | ...compensaciones bastantes importantes`,
  `tackle: Police have launched an initiative to tackle rising crime | Make determined efforts to deal with (a problem or difficult task) (Abordar; Hacer frente)`,
  `without relyng on | Sin depender de`,
  `crowd | Multitud`,
  `you have no clue | No tienes idea`,
  `stay sane | Mantente cuerdo`,
  `Despite | A pesar de`,
  `The job hunt | La búsqueda de empleo`,
  `Struggle: There were signs of a struggle and there was a lot of blood around | (Lucha)`,
  `Stale React component state | (previous state, i think so...)`,
  `We can get rid of some of that cruft by... | Get rid of: Deshacerse; `,
  `Cruft | Badly designed, unnecessarily complicated, or unwanted code or software`,
  `flawed | Blemished, damaged, or imperfect in some way (Defectuoso)`,
  `move around`,
  `Ruthlessly | sin piedad`,
  `negligible | So small or unimportantj as to be not worth considering; insignificant (despreciable)`,
  `jitter | Feelings of extreme nervousness`,
  `arose from | Surgió de`,
  `this change shoved off another... | Este cambio empujó a otro`,
  `can seem a bit daunting... | Puede parecer un poco desalentador`,
  `happen off | Suceder`,
  `who paved the way | Que preparó el camino`,
  `Stockpile | A large accumulated stock of goods or materials (Reservas)`,
  `brittle | Hard but liable to break or shatter easily (Fragil)`,
  `wind up | Terminar, concluir`,
  `It all boils down to... | Todo se reduce a...`,
  `to wander | Walk or move in a leisurely, casual, or aimless way (vagar)`,
  `Aimless | Sin rumbo`,
  `Leisurely | Tranquilo, Sin prisa`,
  `to haunt you | Para perseguirte...`,
  `trip each other up | Tropezar unos con otros`,
  `can be reasoned about | Se puede razonar sobre`,
  `outcomes predicted | Resultados previstos`,
  `we get way better... | Nos volvemos mucho mejores`,
  `the market is tough | tough = duro`,
  `come off | Salir`,
  `upbeat | Optimistic`,
  `pump yourself up | Anímate`,
  `highest bidder | Mejor postor`,
  `regarding the... | Con respecto a...`,
  `Companies are biased toward hiring people with right attitude | ...estan dispuestas a contratar...`,
  `strive | Make great efforts to achieve or obtain something (Esforzarse)`,
  `thorough | Complete with regard to every detail, not superficial or partial (Exhaustiva)`,
  `drifted away from... | Se alejó de...`,
  `blissful | Extremely happy; full or joy`,
  `spite: He'd think I was saying it out of spite | A desire to hurt, annoy, or offend someone (Despecho)`,
  `tongue cheek stab | Puñalada en la mejilla`,
  `where can I find the fitting room? | ...probador`,
  `Their shoes don't match their dresses or bags, but it suits them!`,
  `It loked really in style and matched my brown skirt!`,
  `The fitting room's at the end of the shop on the right`,
  `Pure functions are functions which obey two laws | ...obedece a dos leyes`,
  `The fundamental building block we build our applications with`,
  `How would you like to ...`,
  `That's a reasonable price for those shoes`,
  `That word "reasonable" describes an item that is neither cheap nor expensive`,
  `The designer store has a sale on, so prices are more reasonable`,
  `This traffic is the worst I've seen yet, I'd better...`,
  `Would you like a receipt emailed to you?`,
  `Dou you want me to print or email the receipt?`,
  `And the real you made fun of my pie suit | Y la verdad es que te burlaste de mi traje pastel`,
  `The word "crowded" can mean that there are a lot of people or too many people in one place`,
  `The school's sports day is held at a large venue | ...se celebra en un gran recinto`,
  `life out here is very different than life in the city`,
  `I am getting better at (it) | Estoy mejorando`,
  `Around the corner = very close (place)`,
  `There's a new cafe on the way to the university`,
  `She passes a post office whilst travelling to work`,
  `the supermarket is just down the street from my apartment`,
  `I'll get breakfast on the way to work`,
  `the pharmacy is on the other side of the shopping centre`,
  `My parents live ON Quenn Street`,
  `Have you come across any nice places to eat here? | encontrar`,
  `"to come across" means to find something by chance | Encontrar algo por casualidad`,
  `Sometimes we come across something by chance`,
  `Sometimes an especially nice place is not very well known, we can call these places "finds" or "hidden gems"`,
  `What a great find`,
  `Have you tried that new restaurant yet?`,
  `There's a supermarket just down the road from my apartment`,
  `Around the corner from my house is a really nice place..s`,
  `He owes us an appetizzer | Nos debe un aperitivo`,
  `Thanks fot that severance check | Cheque de indemnización`,
  `He used his severance money to start a ...`,
  `that i have some concerns | Tengo algunas preocupaciones`,
  `What i'm getting at, ... | A lo que me refiero...`,
  `my train was delayed by 30 minutes`,
  `Am I able to get a refund?`,
  `We are sorry to announce...`,
  `We are sorry for any incovenience...this may cause`,
  `...has been cancelled due to technical issues...`,
  `We are arranging a replacement bus service for ... | ...arreglando...`,
  `To go away for the weekend.`,
  `I think we'll eat lots of local food at the supermarket`,
  `the workflow here is pretty straightforward`,
  `eavesdropping | Escuchando a escondidas`,
  `He delves into the ... | Profundiza`,
  `This seemingly simple action lies a ... | Esta acción aparentemente simple supone una ...`,
  `with seamless integration... | Con integración perfecta`,
  `By the time you finish...`,
  `A dead giveaway that a function is inpure... | Un claro indicio de que ...`,
  `It was suddenly all the rage | De repente estaba de moda`,
  `If a function were to mutate a property... | Si una función mutara...`,
  `which could screw up something | Que podría arruinar algo`,
  `throughout your career | A lo largo de tu carrera`,
  `take pride in your work | Sientete orgulloso de tu trabajo`,
  `be willing to learn | Estar dispuesto a aprender`,
  `We decided to go away to XXx this weekend`,
  `We arraive at 10pm, if our flights aren't delayed`,
  `do you want me to quickly summarize for you? | Resumir`,
  `step towards | -> `,
  `It gets wiped out in memory | (erased from memory)`,
  `Conversely | (in another hand)`,
  `It's important not to confuse`,
  `We like to go on holiday in the summer`,
  `slight differences`,
  `to go on a cruise | Crucero`,
  `We can use "to go" to suggest travelling and enganging in an activity.`,
  `We use "to go on" for a specific type of journey, especially an organised event`,
  `The phrase "to go to" indicates moving towards a particular destination`,
  `She wants to go camping`,
  `He doesn't want to go on a cruise`,
  `The love to go to the beach`,
  `I'd wager that's some sort of a code... | Apuesto a que es ...`,
  `you may yet meet your match | Es posible que aun conozcas a tu pareja`,
  `Would that be some sort of defense against...?`,
  `subtle change (b is silent) | Cambio sutil`,
  `for the job and hand`,
  `tangled up | Enredado`,
  `mingling data | Mezclando datos`,
  `if the user screw up.. (make a mistake)`,
  `stale data | Obsolete`,
  `It's a lot more clear what's going on | `,
  `rest assured | Está seguro`,
  `they can really add up | Ellos realmente pueden sumar`,
  `dodged | Avoid (someone or something) by a sudden quick movement (Desviar)`,
  `worth a gist | Vale la pena`,
  `Which you've just seen an example of | Del cual acabas de ver un ejemplo`,
  `everything is as it should be`,
  `Scratch the surface`,
  `At the very least | Por lo menos`,
  `It lacks | Carece`,
  `In spite of the fact that... | A pesar del hecho de que...`,
  `at a glance... | De un vistazo`,
  `bump into it | Chocar con eso`,
  `gather together | Reúnanse`,
  `We'll circle back | Daremos la vuelta`,
  `Mark is the least intelligent of my friends`,
  `I want to go to the least dangerous place in the city`,
  `Let's focus on the least difficult problems first`,
  `Angela is the least pretty of them all`,
  `Without further ado | Sin más preámbulos`,
  `She plays late (she interpretes to anyone else)`,
  `Fine, have it your own way | Hazlo a tu manera`,
  `Go past the bakery and the café is on your left | We can use "past" to indicate movement beyond a certain point`,
  `More formal: The bus stop beside the bank; Less formal: The bus stop is next to the bank
    | The prepositions "beside" and "next to" both mean __by the side of something or someone__`,
  `You can tell from his stance he's still aggressive dominant | Se puede decir por su postura que sigue siendo agresivo y dominante`,
  `Seeking revenge | Buscando venganza`,
  `Meantime, let's ponder the crooke's motive | ... reflexionemos sobre el motivo del ladron`,
  `no wonder you fell for that crook's phony promises | No es de extrañar que cayeraas en las falsas promesas de ese ladron`,
  `Out of the question! | Fuera de toda duda!`,
  `My flight doesn't leave until 11pm`,
  `I often spend time with my friends, It will be nice to spend some time together`,
  `I'm sorry I screed up | Siendo haber metido la pata`,
  `Plus 30 degrees fharenheit and rising | Mas 30 grados fahrenheit y subiendo`,
  `So far, so good | Hasta ahora, todo bien`,
  `Verb patterns involve two verbs: a __stative__ verb that refers to a state of mind, and an __action__ verb
    | Stative verbs: to want to ..., to like to..., to decide to..., to hope to... to plan to..., to try to...`,
  `You have never cared about my career | Nunca te ha preocupado mi carrera`,
  `Have they worked at all | ¿Ellos han trabajado?`,
  `Has no one informed her? | ¿Nadie la ha informado?`,
  `How long have you lived here? | ¿Cuánto tiempo has vivido aquí?`,
  `Where have you worked before? | ¿Dónde has trabajado antes?`,
  `Who has helped you this week? | ¿Quién te ha ayudado?`,
  `Why have you not called them ,  Why haven't you called them?`,
  `Shut your filthy mouth | Cierre tu asquerosa boca`,
  `The world is a filthy place | El mundo es un lugar asqueroso`,
  `Our budget turned out to be smaller than we had thought | Nuestro presupuesto resultó ser menor de lo que habíamos pensado`,
  `My bag feels lighter today than yesterday | Mi bolsa se siente más ligera hoy que ayer`,
  `I'm not sure if I'm going to be able to make it | No estoy seguro de si voy a poder hacerlo`,
  `I'm sorry I didn't get to see you | Siendo haber perdido la oportunidad de verte`,
  `Why do I have to pull the heavier suitcase | ¿Por qué tengo que llevar la maleta más pesada?`,
  `Then again, It's nicer to have to much to read than too little | Por otra parte, es mejor tener muchos libros para leer que pocos`,
  `But still, next time I'm going to choose the suitcase that's smaller | Aún así, la próxima vez que voy elegiré la maleta que sea más pequeña`,
  `This is the slowest line I have ever waited in | Esta es la fila más lenta en la que jamás he esperado`,
  `A two hour delay was a bit too much for her`,
  `Which gate does the flight leave from?`,
  `We're kind of counting on your autobiography`,
  `Have you got a minute = Gotta minute`,
  `I have got to go = I gotta go`,
  `We gotta get up at five tomorrow`,
  `Shes has got a boyfriend = She's gotta boyfriend`,
  `You hungry? R: kinda = Are you hungry? R: kind of | mas o menos`,
  `I'm kinda worried, tired, thirsty | Estoy un poco preucupado, cansado, con sed`,
  `You should have asked = You shoulda asked`,
  `I would have helped you = I woulda helped you`,
  `Let me thing about it = Lemme thing about it`,
  `Could you give me a hand? = Could ya gimme a hand?`,
  `Whaddya = what do you, what are you`,
  `What are you going to do this weekend? = Whaddya gonna do this weekend?`,
  `What do you want to have for dinner? = Whaddya wanna have for dinner?`,
  `What do you have to do before work = Whaddya hafta do before work?`,
  `I hafta go to the bank, I gotta go to the bank`,
  `You haven't shared the document with us yet, have you?`,
  `My friends and I went on a road trip to ...`,
  `We planned everything in advance`,
  `On the way there, we went sightseeing in Las Vegas | De camino, hicimos turismo pro Las Vegas`,
  `I've been in a good mood lately | He estado de buen humor recientemente`,
  `He has given me so much of his time | Ha invertido mucho tiempo en mí`,
  `Social workers face many challenges nowadays | Hoy en dia, los trabajadores sociales se enfrentan a muchos desafíos`,
  `Go on an adventure`,
  `good time management skills`,
  `I may take the whole army single-handed | Puede que me lleve a todo el ejercito sin ayuda`,
  `I was heading for an island with wild natives | Me dirigía a una isla con nativos salvajes`,
  `There's something wrong with my computer screen`,
  `Did you manage to connect your phone to the wifi?`,
  `Could you give me a hand with this application?`,
  `I could switch fields for a change, too | Yo también cambiaría de sector`,
  `It's getting a bit boring`,
  `I have never worked anywhere else than in the factory`,
  `I've been looking into jobs in my field`,
  `I was mad at Dwight, I did it out of spite | Yo estaba enfadado con Dwight, lo hice por despecho`,
  `You can not go wrong with a throat punch`,
  `I get a headache when I look at the computer screen for too long`,
  `They have thought this through | Lo han pensado detenidamente`,
  `Larry has finally found his calling | ha encontrado su vocación`,
  `Nothing at work has ever brought me as much joy as this project | Nada me ha traido tanto exito en el trabajo como este proyecto`,
  `I told him not to worry about it too much`,
  `We've come to this conclusion`,
  `I came as soon as I heard what had happened`,
  `I spoke to the staff about the upcoming changes yesterday`,
  `I meant what I said | Yo quise decir lo que yo dije`,
  `This is the most exciting workplace I've ever been in`,
  `Not so much anymore`,
  `Me and my friends used to compete to see who could get the most points`,
  `We'll sprinkle some sugar on the table`,
  `Do you wnat to hang out?`,
  `Olivia is getting along well in her studies | Olivia está llevando bien sus estudios`,
  `job duties | Deberes`,
  `He hung up on me! | Me colgó`,
  `get alongo with somebody, get along in something`,
  `When we heard what had happened, we wanted to find out more`,
  `Keep up the good work!`,
  `Take after | Parecerse a`,
  `How are you holding up? | ¿Cómo lo estás sobrellevando?`,
  `I'm looking forward to it | Tengo muchas ganas, Estoy ansioso`,
  `I think you take after your mother. - Yes, we really look alike`,
  `We haven't had a chance to cath up lately | No hemos tenido oportunidad de ponernos al dia últimamente`,
  `Perhaps our gathering tonight will cheer you up | Quizá nuestra reunión de esta noche te anime`,
  `It's going to be great`,
  `My mother brought me up with lots of love | Mi mamá me crió con mucho amor`,
  `Having twins seems to run in the family | Tener gemelos parece que viene de familia`,
  `We have become closer over time | Nos hemos vuelto cercanas con el paso del tiempo`,
  `He always got on very well with his mother-in-law | El siempre se llevó muybien con su suegra`,
  `I am going to stop sleeping around | Voy a dejar de dormir por ahí (with someone)`,
  `He has been my best frind for five years now`,
  `Yesterday I took my stepson to the movies | Ayer llevé a mi hijastro al cine`,
  `I knew I would like this apartment`,
  `You were supposed to be home at six`,
  `We talked for a while`,
  `I thought we could order pizza`,
  `Do you think those two could be having an affair? | Aventura`,
  `What is the key to a happy marriage?`,
  `The staff is at your service`,
  `We want our employees to be happy and motivaded`,
  `Do you know who your ancestors are?`,
  `My roommates are basically just acquaintances to me`,
  `He became an orphan as a toddler`,
  `Those are my godparents with a random acquaintance of theirs`,
  `No, I mean the picture with the two toddlers`,
  `They're my ancestors, although I don't know exactly who they are `,
  `Toddlers should not be left unsupervised on the playground`,
  `My mother told me that being a single parent in the 1920s was tough`,
  `I'm going on a trip around India`,
  `I didn't see him yesterday either | tampoco lo vi ayer`,
  `Have you heard anything from him? | ¿Has sabido algo de el?`,
  `Did he say anything to you? | ¿Te dijo algo?`,
  `I wonder how my cousins are doing`,
  `I didn't call him yesterday even though I promised to`,
  `I haven't seen him in a very long time`,
  `Has she moved to her own place already?`,
  `Your husband does have an amazing sense of humor | This is not a question`,
  `Every Saturday my roommate would come home late | Cada sábado mi compañero de piso solía llegar a casa tarde`,
  `Used to | Se puede usar para hablar tanto de estados como de hábitos pasados`,
  `Would | Solo se puede usar para hablar de hábitos pasados`,
  `She would dress up as her twin to trick the teachers | Ella se vestía como su gemela para engañar a los profesores`,
  `What was your childhood like?`,
  `I would visit the cows every day and I knew all their names | Iba a ver a las vacas...`,
  `Can you make it to my party on Friday? | When someone asks "Can you make it to...?", they are inviting you to an event`,
  `Sure, count me in!`,
  `Thanks for the invite - we're in!; Lucy says "she's in" for your drinks party; Sure, count us in for drinks later; They said to count them in!
    | Two very common informal expressions you can use to accept a party invitation are "I'm in " and "count me in"`,
  `Can I let you know later?`,
  `Why are you always trying to play it cool? | ¿Por qué siempre intentas actuar como si nada?`,
  `Where have you been hiding yourself?`,
  `How long have you been selling ballons?`,
  `How have you been getting away with this? | ¿Cómo te has salido con la tuya?`,
  `Would you like me to bring anything?`,
  `Thank for the dinner invite`,
  `Sorry, I can't make dinner tomorrow, I have other plans`,
  `I'm afraid I can't make it | We can use "I'm afraid" to help us sound more polite when saying no to an invitation`,
  `I can't decide whether this sign should say --- or ---]`,
  `Would you mind fixing both of our wasing machines while you're here?`,
  `Accommodation will probably be the most expensive part of our trip | El alojamiento será...`,
  `I hope you will join us on the excursion`,
  `Will you take care of the travel arrangements? | ¿Te encargarás de los preparativos para el viaje?`,
  `We will confirm the schedule well in advance | Confirmaremos la planificación con bastante antelación`,
  `Rendering you personally liable | Haciéndote personalmente responsable`,
  `It sounds like we've got plenty of food | Plenty means "a large number" or "more than enough"`,
  `I think we've got some, but we'll need a few more...`,
  `Our budget will not be sufficient to stay at a five star hotel | presupuesto`,
  `You won't get to know the local way of life on a package tour`,
  `I'm going to look up flights tonight | Buscar vuelos`,
  `All the hotels are going to be full this time of the year`,
  `Are you going to visit all the countries on your bucket list? | Lista de deseos`,
  `I think we're going to travel more frequently now that the kids are older`,
  `There's no such things as an affordable but fancy hotel`,
  `We made arrangements that ended up being out of our budget range | Hicimos preparativos que terminaron estado fuera de nuestro presupuesto`,
  `The resort we visited was so shabby | El resort que visitamos estaba tan descuidado`,
  `Yes, and it was neither fancy nor all-inclusive`,
  `That's what the brochure said it should have been like | Según el folleto así debería haber sido`,
  `Next time, let's do better research before making travel arrangements`,
  `Fancy restaurants are often very pricey`,
  `With good planning, it is possible to travel even on a small budget`,
  `I chose a standard room over an en-suite because it's cheaper`,
  `She and I will be in Brazil when you get back from your vacation`,
  `We are leaving at four, so pack your things | Nos iremos a las cuatro ...`,
  `Our flight leaves at nine`,
  `I will give you a ride to the airport`,
  `We will arrive on schedule, I promise`,
  `We went on an excursion to see the local attractions`,
  `Bike rentals are a great way to explore places if the rates aren't too high`,
  `Sometimes they have even invited me into their homes`,
  `I'm often amazed by their hospitality`,
  `The room rates should be roughly the same as last year | ... deberíán ser más o menos las mismas ...`,
  `Did you hear already?`,
  `There will be a major delay in the schedule`,
  `Are there any other trips we could participate in?`,	
  `I'm planning to go on another excursion that starts at four`,
  `Would you like to join me?`,
  `Sounds like a plan!`,
  `My parents are throwing me a party | When talking about organising a party we use the phrase "to throw a party"`,
  `The flight should be on schedule`,
  `Most of the attractions there should be quite inexpensive`,
  `For our vacation, we're staying at a five star hotel`,
  `I'm not going to be able to help you with the bookings`,
  `He was calm despite the pressure oh him`,
  `They have had a lovely vacation`,
  `I'm letting it wash over me | []`,
  `I'll just play along | Te seguiré el juego`,
  `Would you like me to bring anything, Can I bring anything?`,
  `Can I take these liquids on board | Onboard escrito todo junto es un adjetivo, como en "onboard entertainment"`,
  `My flight arrived a few minutes ahead of time`,
  `I hope I won't suffer from motion sickness this time`,
  `Let's wait until all the other passengers have left`,
  `The taxi lines were much longer than I had expected`,
  `I don't feel well enough to travel, as I have been throwing`,
  `Which way is the baggage claim?`,
  `This terminal is easily the most modern one I've ever seen`,
  `That is to say through extorsion or threats | Es decir, mediante extorsión o amenazas`,
  `Make no mistake | Pero no se equivoque`,
  `I hope you're feeling hungry because dinner's ready`,
  `Dig in before it gets cold!, Just help yourself. There's plenty of everything
    | At the dinner table, "help yourself" means that we can start putting food on our plates and we do not have to wait for anyone to serve us.
    We can also say "dig in" which is more informal`,
  `Your glass is empty, can I top it up for you? | "To top up" as a verb as well as a noun: "a top-up"`,
  `Can I top your glass up?, Let me top up your wine glass, Would anyone like a top-up?
    | We use the phrase "Would you like a top-up" or "Can I top you up?" to offer a guest some more drink`,
  `Would you like seconds? | Offering more food`,
  `Do you want a top-up? | Offering more drink`,
  `The earth looks more beautiful when you're in the air`,
  `This is the most chaotic airport I've ever been to`,
  `Her story was more relatable to me | Me identifiqué mas con su historia`,
  `This is the most dangerous part of this city`,
  `She is th emost careless of us three`,
  `That flight took longer than I expected`,
  `These passengers are more demanding than those that we had yesterday`,
  `I've dealt with very difficult pasengers lately`,
  `But the man today was the most challenging one of them all`,
  `He kept on yelling at us with the most annoying voice`,
  `I'm sure he would've just kept on getting more furious`,
  `Direct flights are nicer than those with changes`,
  `I am more helpless in a big airport than my sister is`,
  `Our gate is further away than theirs, Our gate is the furthest one`,
  `How long is the stopover? - Only half an hour - Ok, we'll run as fast as we can`,
  `Let's hope the food isn't absolutely awful`,
  `It is so much less stressful to travel with just a carry-on than with big suitcase`,
  `We have to be extremely quick so that we won't miss our flight`,
  `Your suitcase is far heavier than what is allowed
    | El adverbio "far" tiene un significado más fuerte que "much", far heavier = very much heavier`,
  `I don't feel well enough to travel, as I have been throwing up`,
  `He might be tired enough to be able to sleep on the plane`,
  `Yes!, I did so online, It's much more convenient - I bet, What about our passports?`,
  `They used to be valid for a much longer period of time`,
  `How ususual that they're starting boarding on time`,
  `This airline is hardly ever behind schedule, It's easily the most reliable one | Esta aerolinea casi nunca va con retrado...`,
  `I have to start flying with them more often`,
  `They are suitable for a long time`,
  `Who have a much tighter schedule than us?`,
  `He stood on one leg for three minutes before he lost his balance`,
  `She held my hand`,
  `He has stood in the exact same spot for a ling time now | Lleva mucho tiempo parado en el mismo sitio`,
  `You are holding it in your hand`,
  `It's pouring outside - Yes, it's raining quite a lot`,
  `I don't like mud, but unfortunately my dog does`,
  `I loved jumping in puddles as a kid | charcos`,
  `I wish we had some colder days, I can't stand this heat`,
  `The fog makes it difficult to see far ahead`,
  `In the summer, a cool breeze is more than welcome`,
  `And incidentally, you look every inch a queen | Y por cierto, pareces toda una reina`,
  `head back | Regresarse`,
  `They've already headed back to the hotel`,
  `I bet you have experienced exciting moments during this tip`,
  `We'll be arriving at my place in about ten minutes`,
  `They have forecast a thunderstorm for this weekend`,
  `Don't you think it's freezing cold out there?`,
  `My flowers have frozen due to the cold weather | freeze - froze - frozen`,
  `It's rather chilly in here | Está bastante fresquito acá`,
  `Tim has kept it a secret for over ten years already`,
  `We keep our glasses in that cupboard | Guardamos nuestros vasos en esa alacena`,
  `That book has lain on that table for days now`,
  `She has lain in bed for hours`,
  `That woolly hat would match nicely with your gloves`,
  `Bring your waterproof jacket, it's going to rain in the evening`,
  `Do you remember when he fell off his bike and broke his leg?`,
  `Do you wanna go back out there? | volver a salir`,
  `How hot is this plate?, How cold does Paris get in the winter? | We can use "How" + adjective to ask someone for more detailed information`,
  `How hot does it get where you live?`,
  `How hard was it for you to learh English?`,
  `How long have you lived in this city?`,
  `How far is your house from the center of town?`,
  `How often do you see your parents?`,
  `How long did you spend cooking? | ¿Cuánto tiempo pasaste cocinando?`,
  `How long have you lived in this city?`,
  `It's such a windy day today, isn't it?`,
  `She isn't going to jog with us, is she?
    | Una question tag está formada por un verbo auxiliar (be, have, do o un modal) y un pronombre sujeto (I, she,...) o el sujeto there`,
  `Mark is staying at home today, isn't he? | No olvidar conjugar el verbo de acuerdo a la persona y al tiempo gramatical de la oración principal`,
  `This is a extremely cozy bedroom, isn't it? | Si la oración es positiva, la question tag será negativa`,
  `The weather isn't going to get much better today, is it? | Si la oración es negativa, la question tag será positiva`,
  `That jacked isn't really warm, is it?`,
  `We are staying indoors today, aren't we?`,
  `There were a lot of puddles outside, weren't there?`,
  `There weren't any public restrooms available, were there?`,
  `They haven't been wearing layers even though it's windy, have they?`,
  `You couldn't see I was weaving at you, could you?
    | Si en la oración hay un verbo modal (must, will, should, would, can, could) la question tag tendrá el mismo verbo modal`,
  `My throat is so sore, I feel sick | Me duele la garganta...`,
  `You didn't wear a scarf yesterday, did you?`,
  `I did't even go outdoors - You didn't?, That's odd | ...que raro`,
  `It could still be due to the weather, couldn't it? | De todos modos, podría ser por el clima...`,
  `You forgot to pack your rubber boots, didn't you?
    | Si noy hay un verbo auxiliar en la oración, la question tag estará formada por el verbo DO en su forma correspondiente`,
  `I am using the navigator correctly, aren't I | Si I am aparece en la oración, la question tag será aren't I?`,
  `I am dressed warmly enough, aren't I?`,
  `How may I help you?`,
  `What would you like to have? | ¿Qué le gustaría comer?`,
  `Thank you for ordering from us`,
  `Remember to take the navigator with you as well`,
  `The fog can make it difficult to see far ahead`,
  `My rubber boots are in the truck, aren't they?`,
  `Carol will take good care of the house, won't she?`,
  `People panicked as the fire alarm went off | ...sonó`,
  `We do not know who lit the fire`,
  `Everybody in the office was panicking`,
  `The test cars crashed just as intended`,
  `We'll be arriving at my place in about ten minutes`,
  `Monica fell down on her way to work`,
  `He has grown at least two inches since I last saw him`,
  `We grew lots of herbs in our garden`,
  `Her whole body shook out of fear`,
  `Mike is clumsy and keeps having little accidents all the time | ...es bastante torpe...`,
  `Which brings me to my next invention | Lo que me lleva a mi siguiente invento`,
  `Who are my dessert?, Who ordered this pizza?, Who was eating my dessert?
    | The question word "who" sometimes behaves differently from the others. That's because it can play different roles in a sentence.
    When it's the subject (performing the main verb), "who" goes immediately before the verb and the rest of the question has the same structure as a positive sentence. We don't use "did" + verb in these cases`,
  `Who did you want to invite? | Here "who" is the object and "you" is the subject`,
  `Washing your hands helps prevent illnesses | "help do" and "help to do" are corrects`,
  `The sound of the fire alarm is so loud that you will certainly hear it`,
  `For the sake of safety... | Por motivos de seguridad...`,
  `A bandage helps the wound heal | La venda ayuda a que se cure la herida`,
  `I'm having difficulty breathing | Estoy teniendo difficultades para respirar`,
  `The patient's condition has gotten better now`,
  `Please use goggles for the sake of safety`,
  `He lost a large amount of blood in the accident`,
  `A big crowd of people gathered around the unconscious person`,
  `He was relieved when he saw the light of the emergency exit | Se tranquilizó...`,
  `Your cooking set off the alarm | turn on`,
  `They managed to put out the fire | Ellos consiguieron apagar el fuego`,
  `I asked you to switch the lamp ON, not off`,
  `Who has switched the lamp off? | La mayoría de los phrasal verbs permiten situar el objeto antes o después de la preposición`,
  `I can't believe the alarm went off again | (Turn on) "To go off" también significa explotar o apagarse`,
  `I pulled over to see what had happened | Paré el auto...`,
  `Do you happen to know what set off the smoke detector | ¿Sabes qué disparó el detector de humo?, ¿Sabes por casualidad...?`,
  `Was it your cooking set off the alarm? | ¿Fuiste tu al cocinar...?. To set off también significa "empezar un viaje"`,
  `How would you like it if...? | ¿Que te parecería si ...?`,
  `Let you in on a little secret | Te voy a contar un pequeño secreto`,
  `How many people came to visit you?`,
  `I took me a week to get over my cold | "To get over" can mean to recover from an illness (like a cold)`,
  `I haven't understood anything he has been saying for the past twenty minutes`,
  `I met Stephanie at the café yesterday | Ayer quedé con Stephanie en la cafetería`,
  `We spent like two hours talking there`,
  `We had so much catching up to do | Teniamos mucho que contarnos`,
  `What did you guys talk about?`,
  `This paper won't stick so I need more glue | El papel no se pega...`,
  `The pipe burst | La tubería se rompió`,
  `The glue is non-toxic and can be washed off with water | ...retirarse con agua`, 
  `Perhaps muted color would be better | Tal vez un color apagado sería mejor`,
  `I went with my gut | Me dejé llevar por mi instito`,
  `make them all disappear into thin air | Thin no se traduce`,
  `I have a sore throat`,
  `I have a sore throat from singing too much. I get a headache if I don't drink enough water. I have a pain in my back from working all day
    | We usually use "sore" to describe pain in our throat or muscles. We often use "ache" to talk about pain in our head or muscles. We use "pain in" with any body part`,
  `I have a temperature | We use "to have" when someone is currently experiencing an illness`,
  `I suffer from allergies in the spring | We can use "to suffer from" with an illness or medical condition (like allergies)`,
  `I have a horrible cold at the moment`,
  `I think I've picked up a bug at school
    | "to pick up a bug" is an informal way of saying "to catch a minor illness. It can also be used to describe the moment someone becomes ill, tipycally when an illness is caught in a public place or through casual contact"`,
  `He caught the flu last month, it lasted for two weeks | We can use "to catch" to describe the initial moment or period when someone becomes ill`,
  `I have a sore back`,
  `I suffer from back pain`,
  `I try to use less water in order to be more eco-friendly`,
  `If you purchase disposable cutlery, make sure it is compostable | Si compras cubiertos desechables, asegurate de que sean compostables`,
  `Don't step on the broken glass`,
  `Honestly is an admirable quality in a person
    | La mayoría de los sustantivos abstractos son incontables. En inglés "the" no se usa con sustantivos incontables o plurales para hablar de cosas en general`,
  `Will there ever be peace in the world? | ¿Habrá alguna vez paz en el mundo?`,
  `Did you already let the dog out today?`,
  `Our old couch felt more comfortable`,
  `My sister cur her favorite doll's hair and regrets it now | ...cortó el pelo de su muñeca favorita y ahora se arrepiente`,
  `I have never felt this way before`,
  `She began to write her first book yesterday | Ayer comenzó a escribir su primer libro`,
  `It is one of the most imprtant things I own`,
  `Devices like laptops and phones are such important parts of our lives now`,
  `I got my laptop a couple years ago`,
  `I can bring my laptop with me`,
  `I need to see a doctor about my cough`,
  `I'll make an appointment with the doctor tomorrow`,
  `I'm having the lasagna`,
  `But we always deal with them fairly too | Pero siempre nos ocupamos de ellos de forma justa también`,
  `I can't help thinking of only myself | No puedo evitar pensar solo en mí`,
  `The thought of D being exposed | La idea de que D sea expuesto`,
  `The doctor said to get some rest to recover faster`,
  `It's important to eat well to stay healthy`,
  `You need to keep away from alcohol while taking this medication`,
  `My mother told me to steer clear of smoking | We can use "to steer clear of" to talk about avoiding something because it's harmful`,
  `He tries to avoid going out in the cold | We can use "to avoid" for general advice on avoiding substances, activities or conditions that can be harmful to our health`,
  `I need to keep away from cats because I'm allergic | We often use "to keep away from" with physical things that can cause us harm`,
  `After surgery, you should steer clear of heavy lifting | We use "to steer clear of" to give a stronger warning or to emphasise the importance of avoiding something`,
  `She needs to avoid eating too much sugar`,
  `I got laid off, and now I'm not sure how we can afford our mortgage payments`,
  `This apartment is worth more than you can afford, I'm afraid | Me temo que...`, 
  `In ten years they will be worth twice as much | ...vandrán el doble`,
  `Let's hope so | Esperemos que si`,
  `We just found out that a major investor wants to invest in our company | Acabamos de saber que un gran inversor...`,
  `He sold the shares of his family company at a good profit | ...a un buen precio`,
  `This painting is worth hundres of dollars | Esta pintura vale ...`,
  `Net income is also called take-home pay`,
  `After years of careful budgeting, we finalyy paid off our mortgage |...administrar los ahorros...`,
  `Gross income is the amount of money you earn before any taxes or other deductions`,
  `Let's go grab some burgers before the game | Vayamos por unas ...`,
  `Carl almost choked on a piece of bread`,
  `It's cool - I forgive you | También se puede decir "I'm cool" or "we're cool" para expresar que no hay problemas por resolver`,
  `She's got to be kidding | Tiene que estar bromeando`,
  `Did you hear about the position through a job advertisement or through networking?`,
  `I just need to fill in an application form on the company webiste and send them my resume`,
  `I even have all the necessary qualifications for it`,
  `She has countless interests | Tiene incontables intereses`,
  `She has been trying to fill in the application form for over an hour`,
  `As the company grows, it will become necessary to recruit new people`,
  `We need to employ more workers to achieve our goals`,
  `She started as a trainee before starting in her current position`,
  `It can seem impossible to find information about internships relevant to your career goals`,
  `He used a lot of time to educate himself about different career options`,
  `I tried to plan my career path carefully before ending up in my current position`,
  `I made sure I got an education that is relevant for my career goals`,
  `To gain experience in my field`,
  `Things never go as planned, so many things happened that I couldn't prepare for`,
  `It is compulsory to protect your clothes in a laboratory | Es obligatorio...`,
  `Are you going to fill in the application today?`,
  `I have the qualifications that meet the requirements of the job description | Tengo las cualificaciones que cumplen...`,
  `I'm not going to make this decision for you`,
  `A good education doesn't guarantee happiness`,
  `Breathe in and out`,
  `It hurts my chest every time I breathe in`,
  `Why should we hire you?`,
  `Tell me about a challenge you've faced at work and how you handled it`,
  `What are your strengths and weaknesses?`,
  `I have a job interview coming up next week`,
  `It seems like a good opportunity and I really want them to hire me`,
  `She knows I can take on any challenge | Sabe que puedo enfrentar cualquier reto`,
  `This open position looks like it could be for you`,
  `I'm concerned that I don't have enough references | ...me preocupa...`,
  `He was totally unprepared for the interview`,
  `The former trainee was quite inexperienced | el aprendiz anterior...`,
  `It's impossible to be young and also have a lot of experience`,
  `I'm afraid I'm too inexperienced for this position | Me temo que ...`,
  `yeah, I don't think we can do it either | ...yo tampoco creo que...`,
  `I'm impatiently waiting for the exam results`,
  `I tried to, but I still feel unprepared`,
  `I'm also afraid that I'm too inexperienced for this job after all`,
  `I'm sure that's not the case since you've already made it this far | ...ya que has llegado tan lejos`,
  `On no, you're worrying too much`,
  `I want to return this shirt because doesn't fit me`,
  `I got into the university | Entré a la universidad`,
  `You have to pay your tuition fee as you enroll at the university`,
  `Oh I see. It's taking pretty long, isn't it?`,
  `I think she's getting a bit impatient already | Creo ya se está volviendo un poco impaciente`,
  `Let's hope that the results arrive soon then`,
  `Jamie's friend decided to defer his entry for a year | decidió aplazar su ingreso por un año`,
  `I'm worried I won't be able to pay my tuition fee | Me preocupa no poder pagar...`,
  `He plans to enter a university abroad | Planea entrar en una universidad extranjera`,
  `Maybe somebody will help him make a choice`, 
  `Lauren was overjoyed when she hot her acceptance letter | Lauren estaba llena de alegria cuando...`,
  `Does the applicant meet all the requirements? | ¿Cumple con todas los...`,
  `Employ - employer - employee; interview - interviewer - interviewee; train - trainer - trainee; advise - adviser - advisee;`,
  `Is your former employer going to be there? | ¿Va a estar allí tu antiguo jefe?`,
  `We are going to have a meeting today about development ideas regarding our ways of working | ...para el desarrollo de ideas sobre nuestra forma de trabajar`,
  `Is everyone required to participate?`,
  `The new requirements will concern both the employer and the employees, so everyone should be there, even the trainees`,
  `He is entering university next fall | El entrará a la universidad el proximo otoño`,
  `There is this one very interesting company that is hiring at the moment and I just happened to see ther add`,
  `The texture of this meal makes it easy to swallow | La textura de este plato hace que sea fácil de tragar`,
  `He swallowed the rest of his beer in one gulp`,
  `You need to chew carefully before swallowing`,
  `You shouldn't talk while chewing your food`,
  `We're having meatloaf for dinner tonight`,
  `That friend of Anne's is always so cheerful
    | El doble genitivo se usa cuando la palabra principal está precedida por un artículo indefinido, un pronombre (this, that) o un número`,
  `The man by the wooden counter is a former teacher of mine | El doble genitivo también se puede usar con la preposición "of" y un pronombre posesivo`,
  `That cousin of yours ordered drinks for us all`,
  `That's the only shirt of your sister's that I like`,
  `That Jack is a friend of our family's`,
  `That girl over there is a colleague of my sister's`,
  `A colleague of Peter's waved at us`,
  `In spite of its bitter taste, Julia really likes gin | Las expresiones "in spite of" y "despite" se usan para indicar contraste. Van seguidas de un sustantivo, pronombre o verbon en -ing`,
  `In spite of it being crowded, we went into the bar anyways`,
  `Despite me wanting my steak rare, it was served medium | Despite no lleva preposiciones`,
  `Despite the unusual texture, this pastry is really good`,
  `In spite of being tired, they wanted to celebrate more`,
  `Although he was drunk, he ordered more drinks | También puedes usar "although" para indicar contraste. Pero a diferencia, va seguido del sujeto y del verbo principal`,
  `Although he was careful, he still spilled his drink | ...se le derraó la bebida`,
  `Despite the weather, I'd like to go out for a while`,
  `I'm sure we'll have fun, although we're goung to get really wet`,
  `They really wanted to sit outside, despite the bad weather`,
  `Are we all going to fit on this bench? | ¿Vamos a caber todos en esta banca?`,
  `I suppose we could borrow a few stools from over there | ...tomar prestados algunos taburetes de allá`,
  `I would rather drink lager than ale | Would se usa con Rather para indicar una preferencia`,
  `You shouldn't swallow your food without chewing`,
  `I'm craving chocolate | Tengo antojo de chocolate`,
  `Wouldn't you like something savory instead?`,
  `Shouldn't you at least try it?`,
  `Teaching manners | Enseñando modales`,
  `I always politely remind my friends about proper table manners when we are eating out | Siempre les recuerdo amablemente...`,
  `Wouldn't you like to wait for everyone to get their food before you start to eat?`,
  `Shouldn't you finish chewing before you talk?`,
  `I don't suppose you could pass the bread when you're done? | ¿Podrías pasar el pan cuando hayas terminado?`,
  `My friends keep asking me whether I would rather just eat my myself | ...sighen preguntándomme si prefiero comer solo` ,
  `I fell head over heels | Caí de cabeza`,
  `I didn't get dressed up for the firemen | No me arreglé para los bomberos`,
  `Have you thought about quitting smoking?`,
  `Why don't you cut back on meat? | Reducir el consumo`,
  `Have you tried eating more vitamins?`,
  `Have you thought about seeing a doctor?`,
  `Have you tried restarting your computer?`,
  `I'm taking him home since he's too drunk to drive`,
  `Be careful not to spill your drink | Derramar`,
  `Some music and lights could really liven up the atmosphere`,
  `How about sharing a pitcher of strawberry margarita? | ¿Qué tal si compartimos una jarra...?`,
  `It's customary to leavy a tip for service | Es habitual dejar propina...`,
  `Mario spilled some of his drink on my shirt`,
  `So this guy walks into a bar... | ...entra al bar...`,
  `I'm in this exam and then my phone starts ringing | El presente simple también se usa para contar una anectoda`,
  `The main character spends a summer abroad | El presente simple también se usa para describir una trama`,
  `I met a Turk, two Poles and a Spaniard during my exchange year | año de intercambio`,
  `It's a shame I don't speak any Turkish, Polish or Spanish | Lastima que...`,
  `We overcame the language barrier by using body language | Superamos la barrera de idioma...`,
  `Hay cuatro tipos de condicionales en inglés: cero, primer, segundo y tercer condicional`,
  `Plants dry up if you don't water them
    | Se secan. Condicional cero, se utilizar para hablar de hechos reales o de situaciones que siempre suceden como consecuencia de una determinada condición`,
  `If it's a nice day today, we'll go to the beach | Condicion 1: expresa qué ocurrirá si se cumple la condición`,
  `If I was a superhero, I would fly over the mountains
    | Condicional 2: Expresa condiciones hipotéticas del presente o del futuro que son muy poco probables o imposibles de ocurrir. Cuando el verbo principal de la cláusula con if es "be", es posible utilizar tanto "were" como "was" con I y he/she/it. Con otros pronombres personales se usa siempre la forma "were"`,
  `If the beach was closer, I would go there every day | Condicional 2: Compuesto por una cláusula subordinada con "if" que representa la hipótesis, y por una cláusula principal que describe qué ocurrirá si se cumple la hipótesis`,
  `He would come if he was feeling better | Condicional 2: La clausula subordinada se forma con "if" + pasado simplre. La clausula principal se forma con "would" + verbo en infinitivo. El orden de ambas cláusulas es indiferente`,
  `We would go camping if the weather was warmer`,
  `If I had enough money, I would travel around the world | Condicional 2`,
  `If we were younger, we would have more time for hobbiery | Condicional 2`,
  `I would buy some candy if the shop was still open`,
  `I should mind my own business? | ¿Debería ocuparme de mis propios asuntos?`,
  `It's your funeral | Se usa para decir a alguien que él, y nadie más, tendrá que lidiar con los resultados desagradables de sus propias acciones`,
  `Do you have any recommendations for a sore throat?`,
  `Have you thought about taking any medication?`,
  `Would you miss me if I lived abroad?`,
  `I could buy an island if I won the lottery | En condicional 2, también se puede usar could o might`,
  `If I were a millionaire, I would buy a house in Spain | Si el verbo de la condición es "be", se puede usar "were" y "was" con I y he/she/it`,	
  `If I was a teacher, I wouldn't give any homework`,
  `If I saved more money, I might have enough for a new car next year`,
  `If you were here I wouldn't feel so lonely`,
  `Panda bears are unique to China | ...viven únicamente en China`,
  `Some stereotypes can be really harmful`,
  `French people aren't all like that, it's just a silly stereotype | ...es un estereotipo absurdo`,
  `I can already see the skyscrapers from the airplane window | Ya puedo ver los rascacielos...`,
  `The best way to get to the city is by public transport`,
  `The entry fee was quite inexpensive | La entrada fue bastante barata`,
  `I might rent a scooter | Quizá rente una motoneta`,
  `Don't go too close to the bonfire | No te acerques mucho a la fogata`,
  `She gets freckles from the sun | Le salen pecas por el sol`,
  `She is such a beauty | Ella es toda una belleza`,
  `She has these cure freckles all over her face | pecas`,
  `I really love those little wrinkles around her eyes that appear when she smiles`,
  `Watch out, that box is really heavy | We can use the imperative "watch out" to give a warning`,
  `It takes a while to get used to wearing braces | Lleva untiempo acostumbrarse...`,
  `She always catches people's attention | ...siempre llama la atención...`,
  `I can't stop staring at him | No puedo dejar de mirarle`,
  `That guy over there has been staring at you all night`,
  `I don't stand a chance, She is catching everyone's attention | No tengo oportunidad, ...`,
  `I cannot resist her charm | ...encanto`,
  `He knelt down and proposed to me | kneel - knelt - knelt`,
  `Both the bride and the groom looked stunning | Tanto la novia como el novio se veían guasones`,
  `He is kneeling! Do you think he's about to propose?`,
  `My parents filed for divorce after years of disagreement | ...pidieron el divorcio..`,
  `Would you like me to walk you home? | ¿Quieres que te acompañe a casa?`,
  `Can I walk you home? | ¿Puedo acompañárte a casa?`,
  `you will meet someone when you least expect it`,
  `but I would brag if I were you | pero yo presumiría si fuera tu`,
  `I hardly studied for the test | Apenas estudié...`,
  `Lately he has been going to bed at 10 p.m. `,
  `I've read nearly every book on that shelf | He leído casi todos los libros...`,
  `Jack truly cares about Rosanna | Jack realmente se preocupa por Rosanna`,
  `I've hardly studied this week, so I need to work hard today`,
  `I hardly even know him | Apenas lo conozco`,
  `She wrote her essay very skillfully | Los adverbios de modo responden a la pregunta ¿Cómo?`,
  `I personally think she's very open-minded | Si hay más de un adverbio en una oración, su orden será: modo-lugar-tiempo`,
  `Can we meet there now? | ¿Podemos vernos allí ahora?`,
  `Weren't you supposed to back up these files?`,
  `Why has she bookmarked this page?`,
  `Simon is drinking coffee while updating his computer`,
  `We will surely solve this issue in the end`,
  `You'll sing the anthem, get your mind off of it | ...para que te olvides de el`,
  `Why don't you stick to singing and your little dance moves? | ¿Por qué no te limitas a cantar y a tus pequeños movimientos de baile?`,
  `The minute I hear I have to perform, I get a huge knot in my stomach | En cuanto oigo que tengo que actuar, se me hace un enorme nudo en el estómago`,
  `This website is super confusing`,
  `I only have five percent battery left`,
  `There is so much information that it only confuses him`,
  `The decision will affect five percent of the population`,
  `This printer won't ever be functional again`,
  `What percentage of the visitors end up buying something from our website?`,
  `As the company grows, it will become necessary to recruit new people`,
  `You need to fill in this field`,
  `My internet connection seems to be a bit unstable`,
  `I bought an e-book but it seems that I'm not able to read it`,
  `I'm wondering whether it's because of my bad internet connection or could this be a server error or something`,
  `The sun has already risen and so should you | ...y tu también deberíás`,
  `He rose to his feet as soon as he heard the doorbell | Se levantó en cuanto escuchó el timbre`,
  `Don't spill coffee on the keyboard | No derrames café...`,
  `Where does this cable go?`,
  `I couldn't save the form because I went over the word count | ...porque superaba el límite de palabras`,
  `You can also search the library database by keywords`,
  `I was thinking about going outside to make out... Care to join me? | besarnos...¿Qué dices?`,
  `Does all this information confuse you?`,
  `Luckily I didn't spill all of it`,
  `Did you spill your coffee again?`,
  `He'll never stop coming for you | Nunca dejará de ir por ti`,
  `Some verbs lke "try", "consider", "avoid" and "suggest", as well as prepositions like "about", typically require the following verb to be an "ing" form`,
  `Have you thought about learning how to swim?`,
  `He fixed the computer quiently downstairs during the night | Orden: sujeto-verbo-objeto-modo-lugar-tiempo`,
  `We met briefly at the cafeteria today | Nos reunimos brevemente en la cafetería hoy`,
  `Have you searched for it in the kitchen? | Lo has buscado en la cocina?`,
  `We can't wait for you any longer, we have to go now | no podemos esperarte mas...`,
  `He finally introduced me to his mother`,
  `I don't have time to attend all those lectures | No tengo tiempo para asistir a todas esas clases (Attend no necesita preposición)`,
  `You have too many lectures to attend`,
  `Two of Sasndra's lectures are overlapping, but she wants to attend both of them`,
  `The professor was a bit absent-minded | El profesor estaba un poco distraído`,
  `Can I borrow these three books? | Lend y Borrow tienen significados diferentes. Lend significa "prestar algo a alguien" y Borrow significa "tomar/pedir prestado algo a alguien"`,	
  `Jacob wants to return his loans before the library closes`,
  `I think the article that I printed earlier is not relevant, but this one might be`, 
  `Indeed, it is | De hecho sí`,
  `I have used up my free print quota for this month | He agotado mi cuota...`,
  `We have replaced the plastic straws with biodegradable ones for environmental reasons`,
  `I think that I have lost my library card
    | Recuerda que that puede ser una conjunción que introduce una oración subordinada. Las oraciones subordinadas suelen hacer una afirmación o proporcionar más información sobre la oración principal.
     Cuando that se usa como conjunción, puede omitirse sin que esto cambie el significado de la oración: I think I have lost my library card.`,
  `I borrowed a book that got exceptionally good reviews | That también puede ser un pronombre relativo: That, Who, Which, Whose y Whom`,
  `Customers that don't return their books on time will get a fine | (fine: multa) El pronombre THAT se usa para referirse a personas, animales y cosas, ya sea que estén en singular o plural.`,
  `The person who wrote this essay is a genius | Who puede sustituirse por THAT`,
  `The answers which you gave me were all wrong | WICH`,
  `Emily is lending me her bicycle, which is nice | Which también puede usarse cuando la oración de relative hacer referencia a toda la frase principal`,
  `There goes that professor whose courses are always so demanding | Whose es una forma posesiva que se usa principalmente para hacer referencia a personas, singular o plural`,
  `That's the girl whom I saw cheating on the exam | Whom es la forma objeto de who. Es muy poco habitual y solo se usa en escritos formales como objeto o después de una preposición. Se suele sustituir por Who`,
  `To whom did you lend that pen? | = Who did you lend that pen to?`,
  `Indeed. I have to thank my sister who helped me write this essay`,
  `Without her help you would still be writing it`,
  `By the way | En fin, Por cierto, `,
  `Just to get the taste out of my mouth | solo para quitarme el sabor de la boca`,
  `No one's jamming a needle in me | Nadie me va a clavar una aguja`,
  `That sounds like a lot of work, which isn't my jam | ...trabajo, lo cual no es mi problema`,
  `If you misinterpret the findings, you can arrive at the wrong conclusion | Si interpretas mal los resultados, puedes llegar a una conclusión equivocada`,
  `Some of the students misinterpreted the results and arrived at the wrong conclusion`,
  `The student whose thesis I read is really talented | Whose es una forma posesiva que se usa principalmente para hacer referencia a personas, singular o plural`,
  `Pronombres relativos: THAT: personas, animales, cosas. WHO: personas. WHICH: cosas, frase principal. WHOSE: posesivo de who. WHOM: cuando who es el objeto del verbo`,
  `The professor who is giving this lecture is late`,
  `The student with whom I made this presentation was hard-working and nice`,
  `That is the student with whom I work`,
  `Taylor cheated on our exam, which is not allowed`,
  `I want to borrow books which are inspiring | tomar prestado`,
  `This course is taught by a professor whose daughter I know`,
  `The quotations that you use need references`,
  `Lastly, you have twenty pages of sources, which may be a bit too much`,
  `It was the heat of the moment | el calor del momento`,
  `I wish you good luck in your exam tomorrow`,
  `We wish you the best, They hope for the best, She hopes so
    | We follow the verb "to wish" with someone and with "luck". We follow the verb "to hope" with "for", we can also say "to hope" + "so" in place of "yes" to answer a question`,
  `I have so many questions about my upcoming studies | ...próximos estudios`,
  `How hard-working do I havve to be in my postgraduate program?`,
  `China's nine-year compulsory education policy has made great progress in recent years | compulsory = mandatory = obligatory`,
  `All modules are worth 15 credits | todos lo módulos valen 15 créditos`,
  `The tutorial (that) I attend every Monday is canceled | Los pronombres relativos se puedes omitir cuando el sujeto de la frase principal es diferente al sujeto de la oración de delativo`,
  `The hard-working student that won the prize is really proud of herself | No se puede omitir los pronombres relativos cuando el sujeto de la frase principal es el mismo que el de la oración de relativo`,
  `The fine (which) you have to pay will be significant`,
  `Some students (whom) I know are also attending this lecture`,
  `The tutorial which are on Tuesday are canceled`,
  `The text you had highlighted was asked about in the exam`,
  `I would expect more credits since we have so much to do for this course`,
  `The professor who I spoke to didn't seem to agree with us`,
  `Did you remember to hand in your essay in time? | ¿Te acordaste de entregar tu ensayo a tiempo?`,
  `I met that author whose book I know by heart | Conocí al autor del libro que me sé de memoria`,
  `She is going to cram for her final exams | cram = estudiar intensivamente`,
  `Yeah, me neither | Sí, yo tampoco`,
  `I will just sit here and read until I know the main points by heart | ...hasta que me sepa todos los puntos principales de memoria`,
  `The fall semester ends at the turn of the year | el semestre de otoño termina al final del año`,
  `Her primary concern is her son's education | su principal preocupación es la educación de su hijo`,
  `I'm afraid I disagree with you on this`,
  `I beg to differ | Lamento discrepar`,
  `The majority of the people were against the proposal`,
  `It's easy to work with you, as we agree on almost everything`,
  `I think it went well`,
  `What did you disagree on then? | ¿Sobre qué no estuviste de acuerdo?`,
  `I was against the idea of working overtime`,
  `I suppose any of these clothes would fit me | ...me quedará`,
  `It seems to me that going to university can be a turning point in one's future | ...un punto de inflexión en el futuro de uno`,
  `All or nothing. A simple bet | ...Una simple apuesta`,
  `I would rather book a hotel | While "rather" is followed directly by the basic form of the verb, we need to add "to" between "prefer" and the verb`,
  `I'd rather not go out tonight, He'd prefer not to stay late | To form negative sentences we put "not" after "rather" and "prefer". In all other cases, we put "not" right after "would"`,
  `They wouldn't like to miss the party, I'd prefer not to go on an package tour, We'd rather not hire a car`,
  `Trust me, when this is all over with | ...cuando esto termine`,
  `Put your money where your mouth is | To support what you say by doing something practical`,
  `If you drop the independent inspections | Si dejas las inspecciones independientes`,
  `If you don't hurry up we'll miss the train | We use the "first conditional" when we believe a future situation is real or possible: if-clause/condition (present simple) + main clause/result (future simple)`,
  `Yuck, you're all sweaty | ...estás todo sudorado`,
  `It's important to let your body recover after workouts`,
  `It's important to also do some stretching and let your body recover properly`,
  `That must have hurt`,
  `He caught her off guard | le dio un susto, la tomó desprevenida`,
  `He caught her red-handed | la encontró con las manos en la masa`,
  `Have you hurt yourself? | ¿Te has lastimado?`,
  `But nowadays I eat almost everything, within reason of course | ...dentro de lo razonable, por supuesto`,
  `One yard is a bit less than a meter`,
  `How many pounds have you lost so far? | ¿Cuántos kilos has perdido hasta ahora?`,
  `Hanna steps on the scale to find out her weight | Hanna se sube a la báscula para saber su peso`,
  `We're going to cram for the exams all night | cram = estudiar intensivamente`,
  `The race is going to be really tight | ...la carrera va a ser muy igualada`,
  `I always aim for the gold medal | Siempre aspiro a la medalla de oro`,
  `This was a very disappointing loss for him, who wanted to win`,
  `I wonder if there is a public toilet anywhere near here`,
  `They may already be on their way | Ya deben estar en camino`,
  `No, you may not go there | No puedes ir allá (may + not)`,
  `She may start a diet`,
  `Might I see yor gold medal, please? | Might tiene un significado parecido a may, pero expresa un mayor grado de cortesía`,
  `Might I > May I > Could I > Can I | De mayor a menor grado de cortesía`,
  `He might be taller than you | Para expresar posibilidad, usa might cuando sea remota y may cuando sea mayor`,
  `It might rain tomorrow. Look at the clouds, It may rain soon | Might probabilidad más remota, may probabilidad mayor`,
  `It will rain, It may rain, It might rain | Lloverá, Es posible que llueva, Podría llover`,
  `Shall we do some stretching? | Shall: Para hacer una sugerencia en forma de pregunta con I o We`,
  `No one shall enter the premises without permission | Cuando el sujeto no es I o We, solo se usa para hacer predicciones o dar órdenes de manera formal`,
  `You might want to try this one | Might: Con sujetos distintos a I y We, puede usarse para hacer sugerencias`,
  `They may not be able to beat their opponents`,
  `You might want to call her and explain everything | Solo se puede usar SHALL para hacer sugerencias cuando el sujeto es I o We. Con otras personas puedes usar might u otro`,
  `You will need to register in order to get the full version`,
  `You need to restart your computer before using the new program`,
  `The kids were jumping all over the place`,
  `Will you participate in the race? | El verbo "participate" necesita la preposición "in"`,
  `I must say that the last round was really tough, though | Aunque debo decir que la última ronda fue realmente dura`,
  `Using only self-defense techniques, she overcame the attacker | someter`,
  `He has to finish this by Friday | Tiene que terminar esto para el viernes`,
  `You've got to stop doing that | Tienes que dejar de hacer eso. Se puede usar "have/has got to" ('ve/'s got to) en lugar de "have to" para hablar de manera informal`,
  `I've got to do it | Tengo que hacerlo`,
  `I'm sure she has just forgotten to reply to you, as always | ..., como siempre`,
  `No one has ever stolen anything from me`,
  `It feels like he hasn't quite forgiven me yet | Parece que todavía no me ha perdonado`,
  `He was so cute that I forgave him right away | ...lo perdoné de inmediato`,
  `He described his feelings through metaphors`,
  `I haven't eaten all day, yet I'm not hungry | Aún así. Las conjunciones coordinadas como or, nor, y yet, unen dos cláusulas principales`,
  `He's such a serious person, yet he always makes me laugh | aún así`,
  `Rose cannot attend the meeting, for she's interviewing the candidates | For como conjunción significa "porque", aunque así se usa más en contextos formales y literarios`,
  `I don't eat meal, nor do I use any dairy products | Nor para unir dos cláusulas negativas. El orden de las palabras se invierte en la última frase después de nor: nor do I`,
  `I had to go grocery shopping, for we had run out of milk`,
  `I bought all kinds of stuff, yet I forgot to buy the milk | Aún así`,
  `Now I can't eat my cereal, nor can I drink my morning coffee`,
  `Whenever you mention this topic, I get mad | Siempre que mencionas este tema, me enojo`,
  `Once you finish your breakfast, we can leave | ...podemos irnos`,
  `We can't do anything unless they give us permission`,
  `No, though I've planning to | No, aunque he pensado en hacerlo`,
  `Should we see it some time tomorrow?`,
  `Yeah, whenever's best for you | Cuando sea mejor para ti`,
  `Whenever I start a new series, I always get bored after a few episodes`,
  `Paula has some insighful comments about the movie | comentarios enclarecedores`,
  `The director's debut film is as suspenseful as it is thought-provoking | da de que pensar`,
  `Some of the more violent scenes were rather distasteful`,
  `My favorite movies from childhood seem outdated now | or not age well`,
  `The movie got better towards the end | ...mejoró hacia el final`,
  `That made me see it in a different light | ...me dio una nueva perspectiva`,
  `It can be seen as pretentious in many situations`,
  `It started raining, It started to rain: There are some verbs that we can use with either "ing" or "to + verb", with no change in meaning, like "begin", "start", "go", "work" or "continue"`,
  `We started dating in 2020 and continued to date until today`,
  `I remember playing with my cousins (to recall an event) !== Please remember to use gloves (to be reminded)`,
  `Try eating with chopsticks (to attempt something) !== Try to come a bit earlier (to make an effort)`,
  `She stopped crying (to cease doing something) !== Can we stop to buy some water? (to take a break)`,
  `While driving home, I stopped to buy some milk: We use "stop to" to show we ended one action in order to begin another one`,
  `We stopped eating in this restaurant because it wasn't good: "to stop" + "ing" to talk about ceasing an activity or habit`,
  `Nowadays, English speakers might follow the verbs "to like", "to love" and "to hate" with an "ing" verb or with "to" + verb. The meaning of these verb patters are very similar, so can be used interchangeably`,
  `She was tired from work, so she went straight to bed | se fue directamente a la cama`,
  `That must be it, I've been looking for them for 30 minutes already | Eso debe ser, he estado buscando desde hace 30 minutos`,
  `Are you finished with those errands yet? | ¿Ya terminaste con esas tareas?`,
  `All done with those errands? | ¿Ya terminaste con esas tareas?`,
  `I'm planning a surprise getaway for my husband's birthday | A getaway is a short holiday`,
  `Do you have a comprehensive plan for organizing the event? | ¿Tienes un plan completo para organizar el evento?`,
  `Yes, everything is being taken care of`,
  `Can you send me a comprehensive list of the supplies we need? | ¿Puedes enviarme una lista completa de los suministros que necesitamos?`,
  `The attendees were asked to register for the event in advance | Los asistentes se les pidió que se registraran para el evento con anticipación`,
  `She can't lift this piano on her own | Ella no puede levantar este piano sola`,
  `Are you able to drive a tractor?, Can you drive a tractor? | Con objetos inanimados es preferible usar can/could`,
  `Have you been able to make time for your hobbies? | Para hablar de una habilidad, usa can en presente simple y could en pasado simple. Con los demás tiempos verbales debes usar "be able to"`,
  `I locked myself out of my apartment, but I was able to get in through the window | Me quedé afuera... Para hablar de una habilidad en una situación específica del pasado, usa "be able to" en lugar de could cuando la oración sea positiva`,
  `Even after a long car chase, the police couldn't catch the criminal | En oraciones negativas pasadas se puede usar también "be able to"`,
  `I haven't been able to sleep since they started construction next door`,
  `Were you able to call your dentist during office hours? | ¿Pudiste llamar a tu dentista durante las horas de oficina?`,
  `I might be able to join you later | Quizá pueda unirme más tarde`,
  `Getting this job requires being able to speak English`,
  `I can't see anything from these seats | Con verbos relacionados con los sentidos o pensar, es más comun usar can y could que be able to: see, hear, understand y believe`,
  `I would like to be able to play the violin`,
  `Has she told you who's going to get the promotion?  | ¿Te ha dicho quién va a conseguir el ascenso?`,
  `Are you with me so far?, Do you follow? | Me sigues hasta ahora?`,
  `I'll go straight to the point`,
  `I haven't been acting strange`,
  `She has been doing some weird things`,
  `I barely see my kids`,
  `We're not going to make it | No lo vamos a lograr`,
  `This isn't going to make it any easier`,
  `We use "yet" and "already" to talk aboit general life experiences until now`,
  `and yet you know there is a side of her that could just curl up on a couch | Y sin embargo, sabes que hay un lado de ella que puede enrollarse en un sofá`,
  `It's not fair that they're trapped in a place like this | No es justo que estén atrapados en un lugar como este`,
  `I haven't been to Asia yet | "Yet" means "until now" and it's usually used in negative sentences`,
  `Let's haul out | Salgamos`,
  `She's a little bit weird, to say the least | ...por decir algo`,
  `No longer alive = dead`,
  `I've been to USA already, but not Canada`,
  `What do you think happened to it? | ¿Qué crees que haya pasado con él?`,
  `What do you take me for? | ¿Qué me crees que soy?, por quien me tomas?`,
  `What do you see in me? | ¿Qué ves en mí?`,
  `He owes his brother ten dollars | debe`,
  `They need to withdraw their salary and divide it into two parts`,
  `I regret not taking care of my finances`,
  `Remember that you still owe me for the gas`,
  `Could you please assist me with filling in these forms? | assist = ayudar, attend = asistir (al algo)`,
  `What is their stance on the uneven distribution of wealth? | ¿Cuál es su posición sobre la desigual distribución de la riqueza?`,
  `We're saving for the down payment on our new house`,
  `Before I noticed something was wrong, I had transferred a lof of money
    | Podemos usar el pasado perfecto para indicar el orden de los eventos pasados. El pasado perfecto indica la acción más antigua`,
  `She has made her first million by the time she was 20`,
  `Had he talked about it before he left?`,
  `I had never owed any money before that`,
  `It still hadn't rained by the end of March`,
  `You were so in love with Emma back then, weren't you? | En ese entonces`,
  `We just can't see eye to eye on how to use money | no coindicir`,
  `Are we on the same page about this?`,
  `Everyone has to be on board with the plan`,
  `Saving money now will help us down the road | Ahorrar ahora nos ayudará más adelante`,
  `I'm in it for the long haul | Estoy en ello hasta el final`,
  `This investment will benefit us in the long run | En el largo plazo`,
  `significant other | pareja`,
  `...and that you understand each other's behavior and values regarding finances | ...respecto a los valores financieros`,
  `The more openly you talk about money, the better off your relationship will be in the long run
    | Cuanto más abiertamente hables de dinero, mejor será tu relación en el largo plazo`,
  `...and to be aware that you and your partner are going to affect each other's finances | to be aware = estar consciente`,
  `Credit cards can leave you in debt`,
  `If you found that choking hazard poster, just head on home | Choking hazard = peligro de asfixia`,
  `I listened to music during the long car journey to Tijuana | Journey = focuses on the movement from place A to place B`,
  `anxious = afraid = uneasy = concerned`,
  `serious = solemn = severe`,
  `dishonest = deceptive = deceitful = untrustworthy`,
  `impatient = restless = eager`,
  `confident = fearless = self-assured = bold`,
  `talkative = chatty`,
  `An uneasy person doesn't like surprises`,
  `A deceptive person manipulares others for personal gain`,
  `An eager person volunteers for new assignments`,
  `A self-assured person confidently expresses their ideas`,
  `He had never been so dissapointed in his whole life`,
  `He became more and more talkative as the evening went on | ... a medida que avanzaba la noche`,
  `Can we discull this matter later? | ¿Podemos hablar de esto más tarde?`,
  `She doesn't open up to me about personal things | no se sincera`,
  `I doubt he wants to talk about it`,
  `boost your spirits | levantar el animo`,
  `bore (someone) to death`,
  `cry me a river`,
  `grin from ear to ear | Grin es sinónimo de smile, y se puede usar como verbo o como sustantivo`,
  `She cried me a river trying to get me to forgive her`,
  `The lecturer speaks so slowly that he bores the students to death | Bore = aburrir, Bored = (sentirse) aburrido, Boring = (ser) aburrido`,
  `I think we need to discuss this thoroughly
    | ...en profundidad. Discuss se refiere a hablar de algo en detalle, sin que esto implique una pelea o desacuerdo. Discuss = hablar de, Argue = discutir`,
  `I find myself doubting him even when I know he is being honest`,
  `Has she been waiting there the whole day?`,
  `She has been drafting that message for hours`,
  `How long have you been playing baseball now?`,
  `I had not been studying Chinese for long before I moved to China | durante mucho tiempo`,
  `How long had you been waiting for the answer?`,
  `I had been repairing the car for hours when they got back`,
  `He had repaired my bike by the time I got home`,
  `He had been washing that T-shirt for a long time before the stain was gone | mancha`,
  `I hadn't been working on it for more than 30 minutes before they requested a status update`,
  `I hadn't been waiting for long when the store opened`,
  `As a kid, I used to lash out if I lost a game | reaccionar de manera agresiva`,
  `I had to work very hard not to lose my cool | ...para no perder la calma`,
  `She seems anxious and indifferent`,
  `I don't know if he's handling his emotions very well`,
  `I can hardly wait | No puedo esperar`,
  `woe is me | Ay de mi`,
  `The photos on the website nade the hostel look very inviting | inviting = atractivo`,
  `The view from the hotel room was jaw-dropping | jaw-dropping = impresionante`,
  `I proofread your text | I review your text`,
  `Remind me to forward that email | Recuérdame que te envíe ese correo`,
  `Please reply to me quickly`,
  `Remember to proofread your text before sending it`,
  `I will forward your message as soon as possible`,
  `To whom it may concern | A quien corresponda`,
  `I'm sorry to ask this on short notice | Siento pedirlo con poca antelación`,
  `I am writing to you with regard to my recent request | con relación a mi solicitud reciente`,
  `Depends on who you're writing it to. You could say "to whom it may concern" if you don't know who will read it`,
  `To whom it may concern, I'd like to file a complaint concerning your service | Presentar una queja`,
  `End the email politely with "best regards"
    | best regards = Saludos cordiales (más formal), best wishes = mis mejores deseos (menos formal), best = saludos (menos formal)`,
  `Tom had been standing at the bus stop for hours when the bus arrived`,
  `What has he been working on this week?`,
  `She hadn't been sleeping at all when she finally went to the doctor's`,
  `I have been enjoying the sunshine for the past half hour or so`,
  `You haven't been playing the mandolin for very long`,
  `How long had you been working there before they promoted you?`,
  `I hadn't been jogging for long when I bumped into my friend`,
  `The team hasn't been meeting deadlines consistently | No han estado cumpliendo plazos de forma consistente`,
  `I've been expecting you`,
  `How has it been going with the email?`,
  `Have you had a chance to get started?`,
  `I've been working on it for the last hour, so it should be ready by the end of the day`,
  `They had been working overtime to meet the deadline | cumplir con la fecha límite`,
  `I hadn't seen the email until she showed me`,
  `I had been having issues with not receiving group emails, but guess how I solved it | ... pero adivinen como lo resolví`,
  `I'd been wondering why I wasn't being kept in the loop | ... por qué on me mantenía informado`,
  `I wonder which option would have the best outcome | ... que opción tendría el mejor resultado`,
  `I need to think it through before proceeding`,
  `Can I get your advice? | ¿Podría pedirte consejo?`,
  `We could discuss this ad infinitum, but let's stop here`,
  `We approached the matter cautiously | approach = abordar, acercarse`,
  `I'm stuck in a rut doing the same things every day`,
  `I'd like to request a status update`,
  `Just writing to ask if you're still available to meet next week`,
  `Justo popping in your inbox to remind you about the deadline | popping in = aparecer de repente`,
  `Just writing to ask if your company is hiring at the moment`,
  `Please do not hesitate to contact me`,
  `despite my best efforts | a pesar de mis mejores esfuerzos`,
  `we regret to inform you | lamentamos informarte`,
  `be of further assistance | ser de mayor ayuda`,
  `Please don't hesitate to contact me if you have any questions`,
  `This is just a quick reminder to RSVP to the event`,
  `The tiny kitchen left much to be desired`,
  `The eyewitness account of the crime was somewhat misleading`,
  `An eyewitness saw the events take place`,
  `A news anchor has to remain calm under pressure | mantener la calma bajo presión`,
  `Breaking news is reported right after it happens`,
  `My daughter is going to a concert this weekend -> He told me that his daughter was going to a concert this weekend`,
  `I saw yesterday -> He told me that he had seen me the day before`,
  `I went to the gym today -> He said that he had gone to the gym that day`,
  `I have gone to the gym many times -> She said that she had gone to the gym many times`,
  `We ate too much at the buffet -> She said they had eaten too much at the buffet`,
  `The children hadn't been sleeping for long when we came home`,
  `I go to the gym every day -> She said she goes to the gym every day`,
  `He is an athlete -> She said he is an athlete`,
  `He said he will get back to me tomorrow -> He said he would get back to me tomorrow`,
  `He said he didn't like books about dystopian societies, but he seems to love this one`,
  `I told them we had thanked everyone in person already`,
  `We have never seen anything like this -> The reporter said they had never seen anything like it`,
  `I will learn French -> She said she would learn French, but she learned Spanish instead`,
  `And we have breaking new just in:`,
  `...in the past half hour | ...en la última media hora`,
  `What is believed to be as... | lo que se cree que es...`,
  `...where the country fair is being held | ...donde se celebra la feria del país`,
  `They are advised to drive cautiously and to report any sightings of sheep to the police`,
  `The police recommend not to approach them | recomendar no acercarse a ellos`,
  `The eyewitness said the robber came out of nowhere`,
  `Describe your physical appearance`,
  `crackdown = a serious attempt to prevent future crimes`,
  `skyrocket = to increase very quickly`,
  `rampage = a violent attack`,
  `budget = a plan of how to spend money, a specific limit relating to how much money to spend`,
  `A good lawyer defends his clients, no matter what`,
  `Suzanne has to wait in twenty-five people | tiene que atender a...`,
  `Who does she talk to about her problems?`,
  `Who do you give a gift to every Friday?`,
  `thirty-eight dollars and ninety cents`,
  `We pay the bills on the 5th of every month`,
  `I contact my clients on a weekly basis | contactar a mis clientes semanalmente`,
  `Before taking off, we always have to check the safety procedures | antes de despegar, siempre tenemos que revisar los procedimientos de seguridad`,
  `It's a gross | Es un asco`,
  `Had time to bond and be charming | había tiempo para acercarse y ser encantador`,
  `All that said, the price was good for the area... | All that said: useful way to transition from a negative tone to a positive one`,
  `All in all, the value of the hostel is great, but... | All in all: is na nice way to begin a summary at the end of a review`,
  `She wanted to know why I had done that`,
  `They asked me when I had come home`,
  `Have you seen my mother? -> He asked me if I had seen his mother`,
  `Do they like pasta? -> He asked me if they like pasta`,
  `Did they leave already? -> She asked us if they had already left`,
  `Don't you like ice cream? -> She asked him if he doesn't like ice cream`,
  `Have you read that book? -> She asked me if I had read that book`,
  `They asked me whether I had found a job`,
  `Where do you work? -> She asked me where I work`,
  `Why didn't you tell me this earlier? -> She asked me why I hadn't told her that earlier`,
  `How long have they been dating? -> She asked us how long they've been dating`,
  `Nice weather we've been having, huh?`,
  `It's a scorcher | Es un calor infernal`,
  `It's gorgeous outside | Está precioso afuera`,
  `It's nippy out today | Hoy hace fresco`,
  `It's a little chilly`,
  `It looks small on the outside`,
  `I don't mind, It doesn't bother me, It doesn't matter to me`,
  `Either is fine, it's all the same to me`,
  `I don't have a preference either way`,
  `I don't mind! Either one works`,
  `Could you ask Riley for the inside scoop? | ¿Podrías conseguir información directa de Riley?`,
  `She has been sulking in her room all day | ha estado de mal humor...`,
  `It's so sad I start to tear up just thinking about it | Es tan triste que se me llenan los ojos de lágrimas...`,
  `She dyed her hair purple on a whim | Se tiño el pelo por impulso`,
  `Their credid service seems to be trustworthy | confiable`,
  `You won't regret joining | No te arrepentirás de unirte`,
  `How can I tell if the seller is trustworthy? | ¿Cómo puedo saber si el vendedor es confiable?`,
]